declare module "net.minecraft.world.level.dimension.DimensionType$MonsterSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DimensionType$MonsterSettings$$Type = ($DimensionType$MonsterSettings);
}

declare module "net.minecraft.world.level.dimension.LevelStem" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LevelStem$$Type = ($LevelStem);
}

declare module "net.minecraft.world.level.dimension.end.EndDragonFight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $EndDragonFight$$Type = ($EndDragonFight);
}

declare module "net.minecraft.world.level.dimension.end.EndDragonFight$Data" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $EndDragonFight$Data$$Type = ($EndDragonFight$Data);
}

declare module "net.minecraft.world.level.dimension.DimensionType" {
import { $ResourceLocation, $ResourceLocation$$Type } from "net.minecraft.resources.ResourceLocation"
import { $Dynamic$$Type } from "com.mojang.serialization.Dynamic"
import { $Record } from "java.lang.Record"
import { $DimensionType$MonsterSettings, $DimensionType$MonsterSettings$$Type } from "net.minecraft.world.level.dimension.DimensionType$MonsterSettings"
import { $ResourceKey, $ResourceKey$$Type } from "net.minecraft.resources.ResourceKey"
import { $TagKey, $TagKey$$Type } from "net.minecraft.tags.TagKey"
import { $OptionalLong, $OptionalLong$$Type } from "java.util.OptionalLong"
import { $Codec } from "com.mojang.serialization.Codec"
import { $Holder } from "net.minecraft.core.Holder"
import { $IntProvider } from "net.minecraft.util.valueproviders.IntProvider"
import { $Block, $Block$$Type } from "net.minecraft.world.level.block.Block"
import { $DataResult } from "com.mojang.serialization.DataResult"
import { $Level } from "net.minecraft.world.level.Level"
import { $Path, $Path$$Type } from "java.nio.file.Path"

export class $DimensionType extends $Record {
static readonly "BITS_FOR_Y": integer
static readonly "CODEC": $Codec<$Holder<$DimensionType>>
static readonly "DIRECT_CODEC": $Codec<$DimensionType>
static readonly "MAX_Y": integer
static readonly "MIN_HEIGHT": integer
static readonly "MIN_Y": integer
static readonly "MOON_BRIGHTNESS_PER_PHASE": float[]
static readonly "WAY_ABOVE_MAX_Y": integer
static readonly "WAY_BELOW_MIN_Y": integer
static readonly "Y_SIZE": integer

constructor(optionalLong0: $OptionalLong$$Type, boolean1: boolean, boolean2: boolean, boolean3: boolean, boolean4: boolean, double5: double, boolean6: boolean, boolean7: boolean, int8: integer, int9: integer, int10: integer, tagKey11: $TagKey$$Type<$Block$$Type>, resourceLocation12: $ResourceLocation$$Type, float13: float, monsterSettings14: $DimensionType$MonsterSettings$$Type)

public "ambientLight"(): float
public "bedWorks"(): boolean
public "coordinateScale"(): double
public "effectsLocation"(): $ResourceLocation
public "fixedTime"(): $OptionalLong
public static "getStorageFolder"(resourceKey0: $ResourceKey$$Type<$Level>, path1: $Path$$Type): $Path
public static "getTeleportationScale"(dimensionType0: $DimensionType$$Type, dimensionType1: $DimensionType$$Type): double
public "hasCeiling"(): boolean
public "hasFixedTime"(): boolean
public "hasRaids"(): boolean
public "hasSkyLight"(): boolean
public "height"(): integer
public "infiniburn"(): $TagKey<$Block>
public "logicalHeight"(): integer
public "minY"(): integer
public "monsterSettings"(): $DimensionType$MonsterSettings
public "monsterSpawnBlockLightLimit"(): integer
public "monsterSpawnLightTest"(): $IntProvider
public "moonPhase"(long0: long): integer
public "natural"(): boolean
/** @deprecated */
public static "parseLegacy"(dynamic0: $Dynamic$$Type<any>): $DataResult<$ResourceKey<$Level>>
public "piglinSafe"(): boolean
public "respawnAnchorWorks"(): boolean
public "timeOfDay"(long0: long): float
public "ultraWarm"(): boolean
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.DimensionType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.DimensionTypeTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DimensionType$$Type = ($DimensionType | Special.DimensionType);
}

