declare module "net.minecraft.world.level.levelgen.heightproviders.HeightProviderType" {
import { $BiasedToBottomHeight } from "net.minecraft.world.level.levelgen.heightproviders.BiasedToBottomHeight"
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $VeryBiasedToBottomHeight } from "net.minecraft.world.level.levelgen.heightproviders.VeryBiasedToBottomHeight"
import { $TrapezoidHeight } from "net.minecraft.world.level.levelgen.heightproviders.TrapezoidHeight"
import { $UniformHeight } from "net.minecraft.world.level.levelgen.heightproviders.UniformHeight"
import { $WeightedListHeight } from "net.minecraft.world.level.levelgen.heightproviders.WeightedListHeight"
import { $ConstantHeight } from "net.minecraft.world.level.levelgen.heightproviders.ConstantHeight"
import { $HeightProvider, $HeightProvider$$Type } from "net.minecraft.world.level.levelgen.heightproviders.HeightProvider"

export interface $HeightProviderType<P extends $HeightProvider = $HeightProvider> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.HeightProviderType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.HeightProviderTypeTag
}

export namespace $HeightProviderType {
const BIASED_TO_BOTTOM: $HeightProviderType<$BiasedToBottomHeight>
const CONSTANT: $HeightProviderType<$ConstantHeight>
const TRAPEZOID: $HeightProviderType<$TrapezoidHeight>
const UNIFORM: $HeightProviderType<$UniformHeight>
const VERY_BIASED_TO_BOTTOM: $HeightProviderType<$VeryBiasedToBottomHeight>
const WEIGHTED_LIST: $HeightProviderType<$WeightedListHeight>
}
export abstract class $HeightProviderType$$Static<P extends $HeightProvider = $HeightProvider> implements $HeightProviderType<P> {
static readonly "BIASED_TO_BOTTOM": $HeightProviderType<$BiasedToBottomHeight>
static readonly "CONSTANT": $HeightProviderType<$ConstantHeight>
static readonly "TRAPEZOID": $HeightProviderType<$TrapezoidHeight>
static readonly "UNIFORM": $HeightProviderType<$UniformHeight>
static readonly "VERY_BIASED_TO_BOTTOM": $HeightProviderType<$VeryBiasedToBottomHeight>
static readonly "WEIGHTED_LIST": $HeightProviderType<$WeightedListHeight>

}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $HeightProviderType$$Type<P extends $HeightProvider = $HeightProvider> = ($HeightProviderType<P> | Special.HeightProviderType | (() => $Codec$$Type<P>));
}

declare module "net.minecraft.world.level.levelgen.heightproviders.UniformHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $UniformHeight$$Type = ($UniformHeight);
}

declare module "net.minecraft.world.level.levelgen.heightproviders.VeryBiasedToBottomHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VeryBiasedToBottomHeight$$Type = ($VeryBiasedToBottomHeight);
}

declare module "net.minecraft.world.level.levelgen.heightproviders.ConstantHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ConstantHeight$$Type = ($ConstantHeight);
}

declare module "net.minecraft.world.level.levelgen.heightproviders.HeightProvider" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $HeightProvider$$Type = ($HeightProvider);
}

declare module "net.minecraft.world.level.levelgen.heightproviders.BiasedToBottomHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BiasedToBottomHeight$$Type = ($BiasedToBottomHeight);
}

declare module "net.minecraft.world.level.levelgen.heightproviders.WeightedListHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WeightedListHeight$$Type = ($WeightedListHeight);
}

declare module "net.minecraft.world.level.levelgen.heightproviders.TrapezoidHeight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $TrapezoidHeight$$Type = ($TrapezoidHeight);
}

