declare module "net.minecraft.world.level.levelgen.presets.WorldPreset" {
import { $Codec } from "com.mojang.serialization.Codec"
import { $Holder } from "net.minecraft.core.Holder"
import { $Map$$Type } from "java.util.Map"
import { $Optional } from "java.util.Optional"
import { $LevelStem, $LevelStem$$Type } from "net.minecraft.world.level.dimension.LevelStem"
import { $ResourceKey$$Type } from "net.minecraft.resources.ResourceKey"
import { $WorldDimensions } from "net.minecraft.world.level.levelgen.WorldDimensions"

export class $WorldPreset {
static readonly "CODEC": $Codec<$Holder<$WorldPreset>>
static readonly "DIRECT_CODEC": $Codec<$WorldPreset>

constructor(map0: $Map$$Type<$ResourceKey$$Type<$LevelStem$$Type>, $LevelStem$$Type>)

public "createWorldDimensions"(): $WorldDimensions
public "overworld"(): $Optional<$LevelStem>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenWorldPreset
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenWorldPresetTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WorldPreset$$Type = ($WorldPreset | Special.WorldgenWorldPreset);
}

