declare module "net.minecraft.world.level.levelgen.synth.ImprovedNoise" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ImprovedNoise$$Type = ($ImprovedNoise);
}

declare module "net.minecraft.world.level.levelgen.synth.PerlinNoise" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PerlinNoise$$Type = ($PerlinNoise);
}

declare module "net.minecraft.world.level.levelgen.synth.NormalNoise" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $NormalNoise$$Type = ($NormalNoise);
}

declare module "net.minecraft.world.level.levelgen.synth.NormalNoise$NoiseParameters" {
import { $List$$Type } from "java.util.List"
import { $Codec } from "com.mojang.serialization.Codec"
import { $Holder } from "net.minecraft.core.Holder"
import { $DoubleList, $DoubleList$$Type } from "it.unimi.dsi.fastutil.doubles.DoubleList"
import { $Record } from "java.lang.Record"

export class $NormalNoise$NoiseParameters extends $Record {
static readonly "CODEC": $Codec<$Holder<$NormalNoise$NoiseParameters>>
static readonly "DIRECT_CODEC": $Codec<$NormalNoise$NoiseParameters>

constructor(int0: integer, doubleList1: $DoubleList$$Type)
constructor(int0: integer, double1: double, ...double2s: double[])
constructor(int0: integer, list1: $List$$Type<double>)

public "amplitudes"(): $DoubleList
public "firstOctave"(): integer
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenNoise
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenNoiseTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $NormalNoise$NoiseParameters$$Type = ($NormalNoise$NoiseParameters | Special.WorldgenNoise);
}

declare module "net.minecraft.world.level.levelgen.synth.BlendedNoise" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BlendedNoise$$Type = ($BlendedNoise);
}

declare module "net.minecraft.world.level.levelgen.synth.PerlinSimplexNoise" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PerlinSimplexNoise$$Type = ($PerlinSimplexNoise);
}

