declare module "net.minecraft.world.entity.schedule.Activity" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
export class $Activity {
static readonly "ADMIRE_ITEM": $Activity
static readonly "AVOID": $Activity
static readonly "CELEBRATE": $Activity
static readonly "CORE": $Activity
static readonly "DIG": $Activity
static readonly "EMERGE": $Activity
static readonly "FIGHT": $Activity
static readonly "HIDE": $Activity
static readonly "IDLE": $Activity
static readonly "INVESTIGATE": $Activity
static readonly "LAY_SPAWN": $Activity
static readonly "LONG_JUMP": $Activity
static readonly "MEET": $Activity
static readonly "PANIC": $Activity
static readonly "PLAY": $Activity
static readonly "PLAY_DEAD": $Activity
static readonly "PRE_RAID": $Activity
static readonly "RAID": $Activity
static readonly "RAM": $Activity
static readonly "REST": $Activity
static readonly "RIDE": $Activity
static readonly "ROAR": $Activity
static readonly "SNIFF": $Activity
static readonly "SWIM": $Activity
static readonly "TONGUE": $Activity
static readonly "WORK": $Activity

constructor(string0: string)

public "getName"(): string
get "name"(): string
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.Activity
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.ActivityTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Activity$$Type = ($Activity | Special.Activity);
}

declare module "net.minecraft.world.entity.schedule.Schedule" {
import { $Activity } from "net.minecraft.world.entity.schedule.Activity"

export class $Schedule {
static readonly "EMPTY": $Schedule
static readonly "SIMPLE": $Schedule
static readonly "TOTAL_WORK_TIME": integer
static readonly "VILLAGER_BABY": $Schedule
static readonly "VILLAGER_DEFAULT": $Schedule
static readonly "WORK_START_TIME": integer

constructor()

public "getActivityAt"(int0: integer): $Activity
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.Schedule
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.ScheduleTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Schedule$$Type = ($Schedule | Special.Schedule);
}

