declare module "net.minecraft.world.damagesource.DamageEffects" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DamageEffects$$Type = ($DamageEffects | ("hurt" | "thorns" | "drowning" | "burning" | "poking" | "freezing"));
}

declare module "net.minecraft.world.damagesource.CombatEntry" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CombatEntry$$Type = ($CombatEntry);
}

declare module "net.minecraft.world.damagesource.DamageSources" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DamageSources$$Type = ($DamageSources);
}

declare module "net.minecraft.world.damagesource.DamageType" {
import { $DamageScaling, $DamageScaling$$Type } from "net.minecraft.world.damagesource.DamageScaling"
import { $Codec } from "com.mojang.serialization.Codec"
import { $DamageEffects, $DamageEffects$$Type } from "net.minecraft.world.damagesource.DamageEffects"
import { $DeathMessageType, $DeathMessageType$$Type } from "net.minecraft.world.damagesource.DeathMessageType"
import { $Record } from "java.lang.Record"

export class $DamageType extends $Record {
static readonly "CODEC": $Codec<$DamageType>

constructor(string0: string, float1: float, damageEffects2: $DamageEffects$$Type)
constructor(string0: string, damageScaling1: $DamageScaling$$Type, float2: float)
constructor(string0: string, damageScaling1: $DamageScaling$$Type, float2: float, damageEffects3: $DamageEffects$$Type)
constructor(string0: string, float1: float)
constructor(string0: string, damageScaling1: $DamageScaling$$Type, float2: float, damageEffects3: $DamageEffects$$Type, deathMessageType4: $DeathMessageType$$Type)

public "deathMessageType"(): $DeathMessageType
public "effects"(): $DamageEffects
public "exhaustion"(): float
public "msgId"(): string
public "scaling"(): $DamageScaling
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.DamageType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.DamageTypeTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DamageType$$Type = ($DamageType | Special.DamageType);
}

declare module "net.minecraft.world.damagesource.DamageSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DamageSource$$Type = ($DamageSource);
}

declare module "net.minecraft.world.damagesource.DamageScaling" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DamageScaling$$Type = ($DamageScaling | ("never" | "when_caused_by_living_non_player" | "always"));
}

declare module "net.minecraft.world.damagesource.CombatTracker" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CombatTracker$$Type = ($CombatTracker);
}

declare module "net.minecraft.world.damagesource.FallLocation" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $FallLocation$$Type = ($FallLocation);
}

declare module "net.minecraft.world.damagesource.DeathMessageType" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DeathMessageType$$Type = ($DeathMessageType | ("default" | "fall_variants" | "intentional_game_design"));
}

