name = "C-Tech: Intercontinental Ballistic Greg"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e1791490c126d803b2f97c7f3b9c5da1f6a1081b0fa1286c2d047ec112a79f3"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
