name = "C-Tech: Intercontinental Ballistic Greg"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76a816533e6e296acd1107937ddcf2cb3591cd83495b4e5c8fe262dffa912319"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
