name = "C-Tech: Intercontinental Ballistic Greg"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb940434e06cb4d87bbec5b5bbf05517355c761136f875cd134f88a7087c14e9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
