StartupEvents.registry('block', event => {

    event.create('draconic_framework_casing')
        .textureAll('kubejs:block/draconic_framework_casing')
        .displayName('Draconic Framework Casing')
        .hardness(5).resistance(12)
        .tagBlock('mineable/pickaxe')

    event.create('awakened_framework_casing')
        .textureAll('kubejs:block/awakened_framework_casing')
        .displayName('Awakened Framework Casing')
        .hardness(6).resistance(15)
        .tagBlock('mineable/pickaxe')

    event.create('biogenic_synthesis_casing')
        .textureAll('kubejs:block/biogenic_synthesis_casing')
        .displayName('Biogenic Synthesis Casing')
        .hardness(7).resistance(18)
        .tagBlock('mineable/pickaxe')

    event.create('draconium_wire_coil', 'gtceu:coil')
        .temperature(12600)
        .level(16)
        .energyDiscount(16)
        .tier(9)
        .coilMaterial(() => GTMaterials.get('draconium'))

    event.create('awakened_draconium_wire_coil', 'gtceu:coil')
        .temperature(14400)
        .level(32)
        .energyDiscount(16)
        .tier(10)
        .coilMaterial(() => GTMaterials.get('awakened_draconium'))

    event.create('cumium_wire_coil', 'gtceu:coil')
        .temperature(16200)
        .level(64)
        .energyDiscount(16)
        .tier(11)
        .coilMaterial(() => GTMaterials.get('cumium'))
})
