// Prep chain for gun sub-assemblies (consumed by arms_manufacturer recipes in guns.js).
// Receiver/Fire Control: Assembler. Barrel: Lathe (boring/turning the rod).
// Material per tier matches what guns.js already uses predominantly at that tier.
ServerEvents.recipes(event => {

    event.recipes.gtceu.assembler('gun_receiver_lv')
        .itemInputs('3x gtceu:wrought_iron_plate', '2x gtceu:wrought_iron_bolt', 'gtceu:wrought_iron_ring')
        .itemOutputs('1x kubejs:lv_gun_receiver')
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.assembler('gun_receiver_mv')
        .itemInputs('3x gtceu:steel_plate', '2x gtceu:steel_bolt', 'gtceu:steel_ring')
        .itemOutputs('1x kubejs:mv_gun_receiver')
        .duration(100)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(1)

    event.recipes.gtceu.assembler('gun_receiver_hv')
        .itemInputs('3x gtceu:stainless_steel_plate', '2x gtceu:stainless_steel_bolt', 'gtceu:stainless_steel_ring')
        .itemOutputs('1x kubejs:hv_gun_receiver')
        .duration(100)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(1)

    event.recipes.gtceu.assembler('gun_receiver_ev')
        .itemInputs('3x gtceu:titanium_plate', '2x gtceu:titanium_bolt', 'gtceu:titanium_ring')
        .itemOutputs('1x kubejs:ev_gun_receiver')
        .duration(100)
        .EUt(GTValues.VA[GTValues.EV])
        .circuit(1)

    event.recipes.gtceu.assembler('gun_receiver_iv')
        .itemInputs('4x gtceu:titanium_plate', '3x gtceu:titanium_bolt', '2x gtceu:titanium_ring')
        .itemOutputs('1x kubejs:iv_gun_receiver')
        .duration(120)
        .EUt(GTValues.VA[GTValues.IV])
        .circuit(2)

    event.recipes.gtceu.assembler('gun_receiver_luv')
        .itemInputs('4x gtceu:naquadah_alloy_plate', '3x gtceu:naquadah_alloy_bolt', '2x gtceu:naquadah_alloy_ring')
        .itemOutputs('1x kubejs:luv_gun_receiver')
        .duration(120)
        .EUt(GTValues.VA[GTValues.LuV])
        .circuit(3)

    event.recipes.gtceu.lathe('gun_barrel_lv')
        .itemInputs('2x gtceu:wrought_iron_rod')
        .itemOutputs('1x kubejs:lv_gun_barrel')
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.lathe('gun_barrel_mv')
        .itemInputs('2x gtceu:steel_rod')
        .itemOutputs('1x kubejs:mv_gun_barrel')
        .duration(100)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.lathe('gun_barrel_hv')
        .itemInputs('2x gtceu:stainless_steel_rod')
        .itemOutputs('1x kubejs:hv_gun_barrel')
        .duration(100)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.lathe('gun_barrel_ev')
        .itemInputs('2x gtceu:titanium_rod')
        .itemOutputs('1x kubejs:ev_gun_barrel')
        .duration(100)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.lathe('gun_barrel_iv')
        .itemInputs('3x gtceu:titanium_rod')
        .itemOutputs('1x kubejs:iv_gun_barrel')
        .duration(120)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.lathe('gun_barrel_luv')
        .itemInputs('3x gtceu:naquadah_alloy_rod')
        .itemOutputs('1x kubejs:luv_gun_barrel')
        .duration(120)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.assembler('gun_fire_control_lv')
        .itemInputs('gtceu:wrought_iron_bolt', '2x gtceu:wrought_iron_ring')
        .itemOutputs('1x kubejs:lv_gun_fire_control')
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.assembler('gun_fire_control_mv')
        .itemInputs('gtceu:steel_bolt', '2x gtceu:steel_ring')
        .itemOutputs('1x kubejs:mv_gun_fire_control')
        .duration(100)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(1)

    event.recipes.gtceu.assembler('gun_fire_control_hv')
        .itemInputs('gtceu:stainless_steel_bolt', '2x gtceu:stainless_steel_ring')
        .itemOutputs('1x kubejs:hv_gun_fire_control')
        .duration(100)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(1)

    event.recipes.gtceu.assembler('gun_fire_control_ev')
        .itemInputs('gtceu:titanium_bolt', '2x gtceu:titanium_ring')
        .itemOutputs('1x kubejs:ev_gun_fire_control')
        .duration(100)
        .EUt(GTValues.VA[GTValues.EV])
        .circuit(1)

    event.recipes.gtceu.assembler('gun_fire_control_iv')
        .itemInputs('2x gtceu:titanium_bolt', '3x gtceu:titanium_ring')
        .itemOutputs('1x kubejs:iv_gun_fire_control')
        .duration(120)
        .EUt(GTValues.VA[GTValues.IV])
        .circuit(2)

    event.recipes.gtceu.assembler('gun_fire_control_luv')
        .itemInputs('2x gtceu:naquadah_alloy_bolt', '3x gtceu:naquadah_alloy_ring')
        .itemOutputs('1x kubejs:luv_gun_fire_control')
        .duration(120)
        .EUt(GTValues.VA[GTValues.LuV])
        .circuit(3)
})
