ServerEvents.recipes(event => {
    event.remove({ mod: 'tacz' })
    event.remove({ mod: 'ars_armorer' })
    event.remove({ mod: 'create_armorer' })
    event.remove({ mod: 'fallout' })
    event.remove({ mod: 'applied_armorer' })
    event.remove({ mod: 'immersive_armorer' })

    // LV: Fallout basic guns

    event.recipes.gtceu.arms_manufacturer('10mm_pistol')
        .itemInputs('2x gtceu:double_wrought_iron_plate', '2x gtceu:wrought_iron_bolt', '3x gtceu:wrought_iron_ring', 'gtceu:treated_wood_plate')
        .inputFluids()
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"fallout:10mm_pistol",HasBulletInBarrel:0b}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.arms_manufacturer('10mm_bullet')
        .itemInputs('32x gtceu:bronze_bolt', '8x minecraft:gunpowder', '32x create:copper_nugget')
        .inputFluids()
        .itemOutputs(Item.of('tacz:ammo', 60, '{AmmoId:"fallout:10mm"}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])
        .circuit(1)

    event.recipes.gtceu.arms_manufacturer('fallout_rifle')
        .itemInputs('6x gtceu:wrought_iron_plate', '2x gtceu:wrought_iron_bolt', '4x gtceu:wrought_iron_ring', 'gtceu:potin_tiny_fluid_pipe', '2x gtceu:treated_wood_plate')
        .inputFluids(Fluid.of('gtceu:distilled_water', 500))
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"fallout:assault_rifle",HasBulletInBarrel:0b}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])
        .circuit(1)

    event.recipes.gtceu.arms_manufacturer('556')
        .itemInputs('24x gtceu:brass_bolt', '6x minecraft:gunpowder', '16x create:copper_nugget')
        .inputFluids()
        .itemOutputs(Item.of('tacz:ammo', 60, '{AmmoId:"tacz:556x45"}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])
        .circuit(1)

    event.recipes.gtceu.arms_manufacturer('trapdoor_rifle')
        .itemInputs('4x gtceu:wrought_iron_bolt', '2x gtceu:wrought_iron_ring', 'gtceu:long_wrought_iron_rod', '5x gtceu:treated_wood_plate')
        .inputFluids()
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"tacz:springfield1873",HasBulletInBarrel:1b}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.arms_manufacturer('4570')
        .itemInputs('24x gtceu:iron_bolt', '3x minecraft:gunpowder', '16x create:copper_nugget')
        .inputFluids()
        .itemOutputs(Item.of('tacz:ammo', 48, '{AmmoId:"tacz:45_70"}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])
        .circuit(1)

    // MV: Create Armorer guns

    event.recipes.gtceu.arms_manufacturer('pistol_revolver_torque')
        .itemInputs('2x gtceu:steel_plate', '3x gtceu:brass_bolt', '2x gtceu:steel_ring', 'create:cogwheel', 'gtceu:treated_wood_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"create_armorer:pistol_revolver_torque",HasBulletInBarrel:0b}'))
        .duration(150)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.arms_manufacturer('pistol_auto_stress')
        .itemInputs('2x gtceu:steel_plate', '4x gtceu:brass_bolt', '2x gtceu:steel_ring', 'create:electron_tube', 'gtceu:treated_wood_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"create_armorer:pistol_auto_stress",HasBulletInBarrel:0b}'))
        .duration(150)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.arms_manufacturer('shotgun_db_stone')
        .itemInputs('3x gtceu:steel_plate', '4x gtceu:brass_bolt', '2x gtceu:steel_ring', '2x create:andesite_alloy', 'gtceu:treated_wood_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"create_armorer:shotgun_db_stone",HasBulletInBarrel:0b}'))
        .duration(150)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.arms_manufacturer('shotgun_pump_bearing')
        .itemInputs('4x gtceu:steel_plate', '4x gtceu:brass_bolt', '3x gtceu:steel_ring', 'create:shaft', 'gtceu:treated_wood_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"create_armorer:shotgun_pump_bearing",HasBulletInBarrel:0b}'))
        .duration(150)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.arms_manufacturer('rifle_assult_crane')
        .itemInputs('6x gtceu:steel_plate', '4x gtceu:brass_bolt', '4x gtceu:steel_ring', 'create:large_cogwheel', 'gtceu:steel_small_fluid_pipe', 'gtceu:treated_wood_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"create_armorer:rifle_assult_crane",HasBulletInBarrel:0b}'))
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.arms_manufacturer('rifle_assult_roller')
        .itemInputs('6x gtceu:steel_plate', '4x gtceu:brass_bolt', '4x gtceu:steel_ring', '2x create:cogwheel', 'gtceu:steel_small_fluid_pipe')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"create_armorer:rifle_assult_roller",HasBulletInBarrel:0b}'))
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.arms_manufacturer('sniper_semi_clockwork')
        .itemInputs('8x gtceu:steel_plate', '4x gtceu:brass_bolt', '3x gtceu:steel_ring', 'gtceu:long_steel_rod', 'create:large_cogwheel', 'gtceu:treated_wood_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"create_armorer:sniper_semi_clockwork",HasBulletInBarrel:0b}'))
        .duration(250)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.arms_manufacturer('sniper_semi_m1')
        .itemInputs('8x gtceu:steel_plate', '4x gtceu:brass_bolt', '3x gtceu:steel_ring', 'gtceu:long_steel_rod', '2x gtceu:treated_wood_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"create_armorer:sniper_semi_m1",HasBulletInBarrel:0b}'))
        .duration(250)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.arms_manufacturer('smg_auto_crank')
        .itemInputs('5x gtceu:steel_plate', '6x gtceu:brass_bolt', '4x gtceu:steel_ring', 'create:shaft', 'create:cogwheel')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"create_armorer:smg_auto_crank",HasBulletInBarrel:0b}'))
        .duration(180)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.arms_manufacturer('mg_platemag_flywheel')
        .itemInputs('10x gtceu:steel_plate', '8x gtceu:brass_bolt', '6x gtceu:steel_ring', 'create:large_cogwheel', 'create:shaft')
        .inputFluids(Fluid.of('gtceu:lubricant', 500))
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"create_armorer:mg_platemag_flywheel",HasBulletInBarrel:0b}'))
        .duration(300)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.arms_manufacturer('gl_revolver_devastator')
        .itemInputs('6x gtceu:steel_plate', '4x gtceu:brass_bolt', '4x gtceu:steel_ring', 'create:shaft', '2x gtceu:steel_large_fluid_pipe')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"create_armorer:gl_revolver_devastator",HasBulletInBarrel:0b}'))
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.arms_manufacturer('cannon_40mm_salamander')
        .itemInputs('10x gtceu:steel_plate', '6x gtceu:brass_bolt', '4x gtceu:steel_ring', '2x gtceu:steel_large_fluid_pipe', 'minecraft:blaze_rod')
        .inputFluids(Fluid.of('gtceu:distilled_water', 1000))
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"create_armorer:cannon_40mm_salamander",HasBulletInBarrel:0b}'))
        .duration(400)
        .EUt(GTValues.VA[GTValues.MV])

    // MV: Create Armorer ammo

    event.recipes.gtceu.arms_manufacturer('slap_ammo')
        .itemInputs('32x gtceu:steel_bolt', '8x minecraft:gunpowder', '32x gtceu:brass_bolt')
        .itemOutputs(Item.of('tacz:ammo', 48, '{AmmoId:"create_armorer:slap"}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(1)

    event.recipes.gtceu.arms_manufacturer('rbapb_ammo')
        .itemInputs('32x gtceu:rubber_plate', '16x gtceu:steel_bolt', '4x minecraft:gunpowder')
        .itemOutputs(Item.of('tacz:ammo', 48, '{AmmoId:"create_armorer:rbapb"}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)

    event.recipes.gtceu.arms_manufacturer('gas_pistol_ammo')
        .itemInputs('16x gtceu:brass_bolt', '8x gtceu:rubber_plate')
        .inputFluids(Fluid.of('gtceu:oxygen', 2000))
        .itemOutputs(Item.of('tacz:ammo', 24, '{AmmoId:"create_armorer:gas_pistol_ammo"}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(3)

    event.recipes.gtceu.arms_manufacturer('12g_ammo')
        .itemInputs('16x gtceu:brass_bolt', '8x minecraft:gunpowder', '16x gtceu:steel_bolt')
        .itemOutputs(Item.of('tacz:ammo', 48, '{AmmoId:"tacz:12g"}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(4)

    event.recipes.gtceu.arms_manufacturer('40mmhe_ammo')
        .itemInputs('8x gtceu:steel_plate', '8x minecraft:gunpowder', '4x minecraft:tnt')
        .itemOutputs(Item.of('tacz:ammo', 8, '{AmmoId:"create_armorer:40mmhe"}'))
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(5)

    event.recipes.gtceu.arms_manufacturer('gernade_ammo')
        .itemInputs('4x gtceu:steel_plate', '4x gtceu:steel_bolt', '8x minecraft:gunpowder')
        .itemOutputs(Item.of('tacz:ammo', 8, '{AmmoId:"create_armorer:gernade"}'))
        .duration(150)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(6)

    // HV: Immersive Armorer guns

    event.recipes.gtceu.arms_manufacturer('pistol_9mm')
        .itemInputs('3x gtceu:stainless_steel_plate', '4x gtceu:aluminium_bolt', '3x gtceu:stainless_steel_ring', 'gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"immersive_armorer:pistol_9mm",HasBulletInBarrel:0b}'))
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('revolver')
        .itemInputs('3x gtceu:stainless_steel_plate', '4x gtceu:aluminium_bolt', '4x gtceu:stainless_steel_ring', 'gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"immersive_armorer:revolver",HasBulletInBarrel:0b}'))
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('standard_rail_pistol_mk2')
        .itemInputs('4x gtceu:stainless_steel_plate', '4x gtceu:aluminium_bolt', '4x gtceu:stainless_steel_ring', '4x gtceu:electrum_plate', 'gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"immersive_armorer:standard_rail_pistol_mk2",HasBulletInBarrel:0b}'))
        .duration(250)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('standard_rail_pistol_mk3')
        .itemInputs('4x gtceu:stainless_steel_plate', '6x gtceu:aluminium_bolt', '4x gtceu:stainless_steel_ring', '6x gtceu:electrum_plate', '2x gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"immersive_armorer:standard_rail_pistol_mk3",HasBulletInBarrel:0b}'))
        .duration(300)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('double_shotgun')
        .itemInputs('4x gtceu:stainless_steel_plate', '4x gtceu:aluminium_bolt', '4x gtceu:stainless_steel_ring', '2x gtceu:treated_wood_plate', 'gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"immersive_armorer:double_shotgun",HasBulletInBarrel:0b}'))
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('pump_shotgun')
        .itemInputs('5x gtceu:stainless_steel_plate', '4x gtceu:aluminium_bolt', '4x gtceu:stainless_steel_ring', '2x gtceu:treated_wood_plate', '2x gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"immersive_armorer:pump_shotgun",HasBulletInBarrel:0b}'))
        .duration(220)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('assult_rifle')
        .itemInputs('6x gtceu:stainless_steel_plate', '6x gtceu:aluminium_bolt', '4x gtceu:stainless_steel_ring', 'gtceu:stainless_steel_small_fluid_pipe', '2x gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"immersive_armorer:assult_rifle",HasBulletInBarrel:0b}'))
        .duration(250)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('railgun')
        .itemInputs('8x gtceu:stainless_steel_plate', '6x gtceu:titanium_rod', '4x gtceu:stainless_steel_ring', '8x gtceu:electrum_plate', '2x gtceu:rubber_plate')
        .inputFluids(Fluid.of('gtceu:lubricant', 1000))
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"immersive_armorer:railgun",HasBulletInBarrel:0b}'))
        .duration(400)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('standard_rail_smg_mk1')
        .itemInputs('6x gtceu:stainless_steel_plate', '6x gtceu:aluminium_bolt', '6x gtceu:stainless_steel_ring', '4x gtceu:electrum_plate', '2x gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"immersive_armorer:standard_rail_smg_mk1",HasBulletInBarrel:0b}'))
        .duration(280)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('short_smg')
        .itemInputs('4x gtceu:stainless_steel_plate', '6x gtceu:aluminium_bolt', '4x gtceu:stainless_steel_ring', '2x gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"immersive_armorer:short_smg",HasBulletInBarrel:0b}'))
        .duration(220)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('plasma_gun')
        .itemInputs('6x gtceu:stainless_steel_plate', '4x gtceu:titanium_rod', '4x gtceu:chromium_plate', '4x gtceu:electrum_plate', 'gtceu:stainless_steel_small_fluid_pipe')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"immersive_armorer:plasma_gun",HasBulletInBarrel:0b}'))
        .duration(350)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('dual_barrel_cannon')
        .itemInputs('10x gtceu:stainless_steel_plate', '6x gtceu:titanium_rod', '6x gtceu:stainless_steel_ring', '2x gtceu:stainless_steel_large_fluid_pipe')
        .inputFluids(Fluid.of('gtceu:lubricant', 2000))
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"immersive_armorer:dual_barrel_cannon",HasBulletInBarrel:0b}'))
        .duration(500)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.arms_manufacturer('chemical_thrower')
        .itemInputs('6x gtceu:stainless_steel_plate', '4x gtceu:aluminium_bolt', '4x gtceu:stainless_steel_ring', '2x gtceu:stainless_steel_fluid_pipe', '2x gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"immersive_armorer:chemical_thrower",HasBulletInBarrel:0b}'))
        .duration(300)
        .EUt(GTValues.VA[GTValues.HV])

    // HV: Immersive Armorer ammo

    event.recipes.gtceu.arms_manufacturer('20mm_ammo')
        .itemInputs('16x gtceu:stainless_steel_bolt', '8x minecraft:gunpowder', '8x gtceu:stainless_steel_ring')
        .itemOutputs(Item.of('tacz:ammo', 24, '{AmmoId:"immersive_armorer:20mm"}'))
        .duration(150)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(1)

    event.recipes.gtceu.arms_manufacturer('burst_capacitor_ammo')
        .itemInputs('8x gtceu:electrum_plate', '4x gtceu:fine_copper_wire', '4x gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:ammo', 16, '{AmmoId:"immersive_armorer:burst_capacitor"}'))
        .duration(150)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(2)

    event.recipes.gtceu.arms_manufacturer('cut_steel_rod_ammo')
        .itemInputs('24x gtceu:stainless_steel_rod')
        .itemOutputs(Item.of('tacz:ammo', 24, '{AmmoId:"immersive_armorer:cut_steel_rod"}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(3)

    event.recipes.gtceu.arms_manufacturer('9mm_ammo')
        .itemInputs('24x gtceu:aluminium_bolt', '8x minecraft:gunpowder', '16x gtceu:lead_bolt')
        .itemOutputs(Item.of('tacz:ammo', 48, '{AmmoId:"tacz:9mm"}'))
        .duration(100)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(4)

    event.recipes.gtceu.arms_manufacturer('high_power_capacitor_ammo')
        .itemInputs('12x gtceu:electrum_plate', '4x gtceu:fine_gold_wire', '6x gtceu:rubber_plate')
        .itemOutputs(Item.of('tacz:ammo', 16, '{AmmoId:"immersive_armorer:high_power_capacitor"}'))
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(5)

    event.recipes.gtceu.arms_manufacturer('454_casul_ammo')
        .itemInputs('24x gtceu:aluminium_bolt', '8x minecraft:gunpowder', '8x gtceu:brass_bolt')
        .itemOutputs(Item.of('tacz:ammo', 32, '{AmmoId:"immersive_armorer:454_casul"}'))
        .duration(120)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(6)

    event.recipes.gtceu.arms_manufacturer('ap_ammo')
        .itemInputs('16x gtceu:titanium_rod', '6x minecraft:gunpowder', '16x gtceu:stainless_steel_bolt')
        .itemOutputs(Item.of('tacz:ammo', 24, '{AmmoId:"immersive_armorer:ap_ammo"}'))
        .duration(150)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(7)

    event.recipes.gtceu.arms_manufacturer('stream_capacitor_ammo')
        .itemInputs('16x gtceu:electrum_plate', '8x gtceu:fine_copper_wire', '4x gtceu:rubber_plate', '2x gtceu:stainless_steel_rod')
        .itemOutputs(Item.of('tacz:ammo', 8, '{AmmoId:"immersive_armorer:stream_capacitor"}'))
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(8)

    event.recipes.gtceu.arms_manufacturer('chemical_ammo')
        .itemInputs('8x gtceu:stainless_steel_bolt', '4x gtceu:rubber_plate')
        .inputFluids(Fluid.of('gtceu:diesel', 1000))
        .itemOutputs(Item.of('tacz:ammo', 8, '{AmmoId:"immersive_armorer:chemical"}'))
        .duration(150)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(9)

    // LuV: Fallout energy weapons

    event.recipes.gtceu.arms_manufacturer('x26')
        .itemInputs('4x gtceu:naquadah_alloy_plate', '4x gtceu:iridium_plate', 'gtceu:luv_emitter', '2x gtceu:chromium_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"fallout:x26",HasBulletInBarrel:0b}'))
        .duration(400)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.arms_manufacturer('laser_pistol')
        .itemInputs('4x gtceu:naquadah_alloy_plate', '4x gtceu:iridium_plate', 'gtceu:luv_emitter', 'gtceu:luv_sensor', '2x gtceu:osmium_plate')
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"fallout:laser_pistol",HasBulletInBarrel:0b}'))
        .duration(400)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.arms_manufacturer('laser_rifle')
        .itemInputs('6x gtceu:naquadah_alloy_plate', '4x gtceu:iridium_plate', '2x gtceu:luv_emitter', 'gtceu:luv_sensor', '2x gtceu:osmium_plate', '2x gtceu:fine_naquadah_wire')
        .inputFluids(Fluid.of('gtceu:helium', 2000))
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"fallout:laser_rifle",HasBulletInBarrel:0b}'))
        .duration(600)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.arms_manufacturer('gauss_rifle')
        .itemInputs('6x gtceu:naquadah_alloy_plate', '4x gtceu:osmium_plate', 'gtceu:luv_electric_motor', '4x gtceu:iridium_plate', '2x gtceu:fine_naquadah_wire')
        .inputFluids(Fluid.of('gtceu:lubricant', 2000))
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"fallout:gauss_rifle",HasBulletInBarrel:0b}'))
        .duration(600)
        .EUt(GTValues.VA[GTValues.LuV])

    // LuV: fusion cell ammo

    event.recipes.gtceu.arms_manufacturer('fusion_cell_ammo')
        .itemInputs('8x gtceu:naquadah_plate', '4x gtceu:osmium_dust', '4x gtceu:iridium_plate')
        .inputFluids(Fluid.of('gtceu:deuterium', 4000))
        .itemOutputs(Item.of('tacz:ammo', 8, '{AmmoId:"fallout:fusion_cell"}'))
        .duration(400)
        .EUt(GTValues.VA[GTValues.LuV])
        .circuit(1)
});
