ServerEvents.recipes(event => {
    event.remove({ mod: 'tacz' })
    event.remove({ mod: 'ars_armorer' })
    event.remove({ mod: 'create_armorer' })
    event.remove({ mod: 'fallout' })
    event.remove({ mod: 'applied_armorer' })
    event.remove({ mod: 'immersive_armorer' })

    event.recipes.gtceu.arms_manufacturer('10mm_pistol')
        .itemInputs('2x gtceu:double_wrought_iron_plate', '2x gtceu:wrought_iron_bolt', '3x gtceu:wrought_iron_ring', 'gtceu:treated_wood_plate')
        .inputFluids()
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"SEMI",GunId:"fallout:10mm_pistol",HasBulletInBarrel:0b}'))
        .duration(100)
        .EUt(30)

    event.recipes.gtceu.arms_manufacturer('10mm_bullet')
        .itemInputs('32x gtceu:bronze_bolt', '8x minecraft:gunpowder', '32x create:copper_nugget' )
        .inputFluids()
        .itemOutputs(Item.of('tacz:ammo', 60, '{AmmoId:"fallout:10mm"}'))
        .duration(100)
        .EUt(30)
        .circuit(1)

    event.recipes.gtceu.arms_manufacturer('fallout_rifle')
        .itemInputs('6x gtceu:wrought_iron_plate', '2x gtceu:wrought_iron_bolt', '4x gtceu:wrought_iron_ring', 'gtceu:potin_tiny_fluid_pipe', '2x gtceu:treated_wood_plate')
        .inputFluids(Fluid.of('gtceu:distilled_water', 500))
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:0,GunFireMode:"AUTO",GunId:"fallout:assault_rifle",HasBulletInBarrel:0b}'))
        .duration(100)
        .EUt(30)
        .circuit(1)

    event.recipes.gtceu.arms_manufacturer('556')
        .itemInputs('24x gtceu:brass_bolt', '6x minecraft:gunpowder', '16x create:copper_nugget' )
        .inputFluids()
        .itemOutputs(Item.of('tacz:ammo', 60, '{AmmoId:"tacz:556x45"}'))
        .duration(100)
        .EUt(30)
        .circuit(1)
});