GTCEuStartupEvents.registry('gtceu:element', event => {
   event.create('magic')
        .protons(-1)
        .neutrons(-1)
        .halfLifeSeconds(-1)
        .decayTo(null)
        .symbol('ᛖ')
        .isIsotope(false)

    event.create('abstract_metal')
        .protons(-1)
        .neutrons(-1)
        .halfLifeSeconds(-1)
        .decayTo(null)
        .symbol('𐲘?')
        .isIsotope(false)

    event.create('elementium')
        .protons(-1)
        .neutrons(-1)
        .halfLifeSeconds(-1)
        .decayTo(null)
        .symbol('Em')
        .isIsotope(false)
})