StartupEvents.registry('item', event => {
    event.create('glowing_compound_dust')
    event.create('impure_glimmering_dust')

    event.create('raw_source_gem')
    event.create('pure_source_gem_dust')
    event.create('rough_source_gem')

    event.create('holy_silver_blend')
    event.create('element_attunement_stone')
    event.create('chaos_essence')

    event.create('magebloom_sieve')

    event.create('weak_elementium_dust')
    event.create('raw_elementite')
    event.create('elementite_dust')

    event.create('florid_compound')
    event.create('living_metalloid')

    event.create('vengeful_gaia_spirit')
    event.create('soul_of_gaia')
    event.create('boundless_gaia_spirit_ingot')
})

GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('ambrosium')
        .gem()
        .color(0xf1ef5f)
        .iconSet(GTMaterialIconSet.CERTUS)
        .flags(GTMaterialFlags.GENERATE_LENS)
        .ore()
    event.create('luminessence')
        .dust()
        .color(0xfafa5d)
        .iconSet(GTMaterialIconSet.SHINY)
    event.create('holy_silver')
        .ingot()
        .color(0xe7f79e)
        .iconSet(GTMaterialIconSet.BRIGHT)
    event.create('prima_materia')
        .ingot()
        .color(0xAEF76D)
        .iconSet(GTMaterialIconSet.SHINY)
    event.create('abstract_metal')
        .ingot()
        .color(0xA2A6A2)
        .secondaryColor(0x505350)
        .iconSet(GTMaterialIconSet.METALLIC)
    event.create('source')
        .gem()
        .ore()
        .color(0xAE44E2)
        .secondaryColor(0xE244C8)
        .iconSet(GTMaterialIconSet.QUARTZ)
        .flags(GTMaterialFlags.GENERATE_LENS, GTMaterialFlags.NO_ORE_SMELTING)
})
