declare module "net.minecraft.world.level.levelgen.structure.structures.ShipwreckStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ShipwreckStructure$$Type = ($ShipwreckStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.RuleTestType" {
import { $BlockStateMatchTest } from "net.minecraft.world.level.levelgen.structure.templatesystem.BlockStateMatchTest"
import { $BlockMatchTest } from "net.minecraft.world.level.levelgen.structure.templatesystem.BlockMatchTest"
import { $AlwaysTrueTest } from "net.minecraft.world.level.levelgen.structure.templatesystem.AlwaysTrueTest"
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $RandomBlockStateMatchTest } from "net.minecraft.world.level.levelgen.structure.templatesystem.RandomBlockStateMatchTest"
import { $RandomBlockMatchTest } from "net.minecraft.world.level.levelgen.structure.templatesystem.RandomBlockMatchTest"
import { $TagMatchTest } from "net.minecraft.world.level.levelgen.structure.templatesystem.TagMatchTest"
import { $RuleTest, $RuleTest$$Type } from "net.minecraft.world.level.levelgen.structure.templatesystem.RuleTest"

export interface $RuleTestType<P extends $RuleTest = $RuleTest> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.RuleTest
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.RuleTestTag
}

export namespace $RuleTestType {
const ALWAYS_TRUE_TEST: $RuleTestType<$AlwaysTrueTest>
const BLOCKSTATE_TEST: $RuleTestType<$BlockStateMatchTest>
const BLOCK_TEST: $RuleTestType<$BlockMatchTest>
const RANDOM_BLOCKSTATE_TEST: $RuleTestType<$RandomBlockStateMatchTest>
const RANDOM_BLOCK_TEST: $RuleTestType<$RandomBlockMatchTest>
const TAG_TEST: $RuleTestType<$TagMatchTest>
function register<P extends $RuleTest>(string0: string, codec1: $Codec$$Type<P>): $RuleTestType<P>
}
export abstract class $RuleTestType$$Static<P extends $RuleTest = $RuleTest> implements $RuleTestType<P> {
static readonly "ALWAYS_TRUE_TEST": $RuleTestType<$AlwaysTrueTest>
static readonly "BLOCKSTATE_TEST": $RuleTestType<$BlockStateMatchTest>
static readonly "BLOCK_TEST": $RuleTestType<$BlockMatchTest>
static readonly "RANDOM_BLOCKSTATE_TEST": $RuleTestType<$RandomBlockStateMatchTest>
static readonly "RANDOM_BLOCK_TEST": $RuleTestType<$RandomBlockMatchTest>
static readonly "TAG_TEST": $RuleTestType<$TagMatchTest>

static "register"<P extends $RuleTest>(string0: string, codec1: $Codec$$Type<P>): $RuleTestType<P>
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RuleTestType$$Type<P extends $RuleTest = $RuleTest> = ($RuleTestType<P> | Special.RuleTest | (() => $Codec$$Type<P>));
}

declare module "net.minecraft.world.level.levelgen.structure.pools.FeaturePoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $FeaturePoolElement$$Type = ($FeaturePoolElement);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity.Passthrough" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Passthrough$$Type = ($Passthrough);
}

declare module "net.minecraft.world.level.levelgen.structure.pools.StructureTemplatePool$Projection" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureTemplatePool$Projection$$Type = ($StructureTemplatePool$Projection | ("terrain_matching" | "rigid"));
}

declare module "net.minecraft.world.level.levelgen.structure.structures.OceanRuinStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $OceanRuinStructure$$Type = ($OceanRuinStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.BlockRotProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BlockRotProcessor$$Type = ($BlockRotProcessor);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.DesertPyramidStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DesertPyramidStructure$$Type = ($DesertPyramidStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.BlockIgnoreProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BlockIgnoreProcessor$$Type = ($BlockIgnoreProcessor);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.WoodlandMansionStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WoodlandMansionStructure$$Type = ($WoodlandMansionStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.StructureCheckResult" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureCheckResult$$Type = ($StructureCheckResult | ("start_present" | "start_not_present" | "chunk_load_needed"));
}

declare module "net.minecraft.world.level.levelgen.structure.pools.JigsawJunction" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $JigsawJunction$$Type = ($JigsawJunction);
}

declare module "net.minecraft.world.level.levelgen.structure.pools.LegacySinglePoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LegacySinglePoolElement$$Type = ($LegacySinglePoolElement);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.JigsawReplacementProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $JigsawReplacementProcessor$$Type = ($JigsawReplacementProcessor);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.PosAlwaysTrueTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PosAlwaysTrueTest$$Type = ($PosAlwaysTrueTest);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.TagMatchTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $TagMatchTest$$Type = ($TagMatchTest);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.LavaSubmergedBlockProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LavaSubmergedBlockProcessor$$Type = ($LavaSubmergedBlockProcessor);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.PosRuleTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PosRuleTest$$Type = ($PosRuleTest);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.CappedProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CappedProcessor$$Type = ($CappedProcessor);
}

declare module "net.minecraft.world.level.levelgen.structure.pieces.StructurePieceType$ContextlessType" {
import { $CompoundTag } from "net.minecraft.nbt.CompoundTag"
import { $StructurePiece$$Type } from "net.minecraft.world.level.levelgen.structure.StructurePiece"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePieceType$ContextlessType$$Type = ($StructurePieceType$ContextlessType | ((arg0: $CompoundTag) => $StructurePiece$$Type));
}

declare module "net.minecraft.world.level.levelgen.structure.pools.StructurePoolElementType" {
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $SinglePoolElement } from "net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement"
import { $LegacySinglePoolElement } from "net.minecraft.world.level.levelgen.structure.pools.LegacySinglePoolElement"
import { $FeaturePoolElement } from "net.minecraft.world.level.levelgen.structure.pools.FeaturePoolElement"
import { $ListPoolElement } from "net.minecraft.world.level.levelgen.structure.pools.ListPoolElement"
import { $StructurePoolElement, $StructurePoolElement$$Type } from "net.minecraft.world.level.levelgen.structure.pools.StructurePoolElement"
import { $EmptyPoolElement } from "net.minecraft.world.level.levelgen.structure.pools.EmptyPoolElement"

export interface $StructurePoolElementType<P extends $StructurePoolElement = $StructurePoolElement> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructurePoolElement
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructurePoolElementTag
}

export namespace $StructurePoolElementType {
const EMPTY: $StructurePoolElementType<$EmptyPoolElement>
const FEATURE: $StructurePoolElementType<$FeaturePoolElement>
const LEGACY: $StructurePoolElementType<$LegacySinglePoolElement>
const LIST: $StructurePoolElementType<$ListPoolElement>
const SINGLE: $StructurePoolElementType<$SinglePoolElement>
function register<P extends $StructurePoolElement>(string0: string, codec1: $Codec$$Type<P>): $StructurePoolElementType<P>
}
export abstract class $StructurePoolElementType$$Static<P extends $StructurePoolElement = $StructurePoolElement> implements $StructurePoolElementType<P> {
static readonly "EMPTY": $StructurePoolElementType<$EmptyPoolElement>
static readonly "FEATURE": $StructurePoolElementType<$FeaturePoolElement>
static readonly "LEGACY": $StructurePoolElementType<$LegacySinglePoolElement>
static readonly "LIST": $StructurePoolElementType<$ListPoolElement>
static readonly "SINGLE": $StructurePoolElementType<$SinglePoolElement>

static "register"<P extends $StructurePoolElement>(string0: string, codec1: $Codec$$Type<P>): $StructurePoolElementType<P>
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePoolElementType$$Type<P extends $StructurePoolElement = $StructurePoolElement> = ($StructurePoolElementType<P> | Special.WorldgenStructurePoolElement | (() => $Codec$$Type<P>));
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity.AppendLoot" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AppendLoot$$Type = ($AppendLoot);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.LinearPosTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LinearPosTest$$Type = ($LinearPosTest);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.OceanMonumentStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $OceanMonumentStructure$$Type = ($OceanMonumentStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.BuriedTreasureStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BuriedTreasureStructure$$Type = ($BuriedTreasureStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.MineshaftStructure$Type" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $MineshaftStructure$Type$$Type = ($MineshaftStructure$Type | ("normal" | "mesa"));
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureTemplateManager$$Type = ($StructureTemplateManager);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.NetherFortressStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $NetherFortressStructure$$Type = ($NetherFortressStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.StructureStart" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureStart$$Type = ($StructureStart);
}

declare module "net.minecraft.world.level.levelgen.structure.StructureSpawnOverride$BoundingBoxType" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureSpawnOverride$BoundingBoxType$$Type = ($StructureSpawnOverride$BoundingBoxType | ("piece" | "structure"));
}

declare module "net.minecraft.world.level.levelgen.structure.pieces.StructurePiecesBuilder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePiecesBuilder$$Type = ($StructurePiecesBuilder);
}

declare module "net.minecraft.world.level.levelgen.structure.StructurePiece" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePiece$$Type = ($StructurePiece);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.IglooStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $IglooStructure$$Type = ($IglooStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.Structure" {
import { $LevelHeightAccessor$$Type } from "net.minecraft.world.level.LevelHeightAccessor"
import { $BiomeSource$$Type } from "net.minecraft.world.level.biome.BiomeSource"
import { $RecordCodecBuilder$Instance$$Type } from "com.mojang.serialization.codecs.RecordCodecBuilder$Instance"
import { $HolderSet } from "net.minecraft.core.HolderSet"
import { $Biome, $Biome$$Type } from "net.minecraft.world.level.biome.Biome"
import { $Function$$Type } from "java.util.function.Function"
import { $PiecesContainer$$Type } from "net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer"
import { $Structure$GenerationContext$$Type } from "net.minecraft.world.level.levelgen.structure.Structure$GenerationContext"
import { $Holder, $Holder$$Type } from "net.minecraft.core.Holder"
import { $WorldGenLevel$$Type } from "net.minecraft.world.level.WorldGenLevel"
import { $MobCategory } from "net.minecraft.world.entity.MobCategory"
import { $Map } from "java.util.Map"
import { $Structure$StructureSettings, $Structure$StructureSettings$$Type } from "net.minecraft.world.level.levelgen.structure.Structure$StructureSettings"
import { $StructureSpawnOverride } from "net.minecraft.world.level.levelgen.structure.StructureSpawnOverride"
import { $GenerationStep$Decoration } from "net.minecraft.world.level.levelgen.GenerationStep$Decoration"
import { $Predicate$$Type } from "java.util.function.Predicate"
import { $RandomSource$$Type } from "net.minecraft.util.RandomSource"
import { $RegistryAccess$$Type } from "net.minecraft.core.RegistryAccess"
import { $ModifiableStructureInfo } from "net.minecraftforge.common.world.ModifiableStructureInfo"
import { $StructureType } from "net.minecraft.world.level.levelgen.structure.StructureType"
import { $ChunkGenerator$$Type } from "net.minecraft.world.level.chunk.ChunkGenerator"
import { $ChunkPos$$Type } from "net.minecraft.world.level.ChunkPos"
import { $Codec } from "com.mojang.serialization.Codec"
import { $StructureTemplateManager$$Type } from "net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager"
import { $RandomState$$Type } from "net.minecraft.world.level.levelgen.RandomState"
import { $BoundingBox, $BoundingBox$$Type } from "net.minecraft.world.level.levelgen.structure.BoundingBox"
import { $Optional } from "java.util.Optional"
import { $RecordCodecBuilder } from "com.mojang.serialization.codecs.RecordCodecBuilder"
import { $StructureManager$$Type } from "net.minecraft.world.level.StructureManager"
import { $Structure$GenerationStub } from "net.minecraft.world.level.levelgen.structure.Structure$GenerationStub"
import { $StructureStart } from "net.minecraft.world.level.levelgen.structure.StructureStart"
import { $TerrainAdjustment } from "net.minecraft.world.level.levelgen.structure.TerrainAdjustment"

export class $Structure {
static readonly "CODEC": $Codec<$Holder<$Structure>>
static readonly "DIRECT_CODEC": $Codec<$Structure>

public "adjustBoundingBox"(boundingBox0: $BoundingBox$$Type): $BoundingBox
public "afterPlace"(worldGenLevel0: $WorldGenLevel$$Type, structureManager1: $StructureManager$$Type, chunkGenerator2: $ChunkGenerator$$Type, randomSource3: $RandomSource$$Type, boundingBox4: $BoundingBox$$Type, chunkPos5: $ChunkPos$$Type, piecesContainer6: $PiecesContainer$$Type): void
public "biomes"(): $HolderSet<$Biome>
public "findValidGenerationPoint"(generationContext0: $Structure$GenerationContext$$Type): $Optional<$Structure$GenerationStub>
public "generate"(registryAccess0: $RegistryAccess$$Type, chunkGenerator1: $ChunkGenerator$$Type, biomeSource2: $BiomeSource$$Type, randomState3: $RandomState$$Type, structureTemplateManager4: $StructureTemplateManager$$Type, long5: long, chunkPos6: $ChunkPos$$Type, int7: integer, levelHeightAccessor8: $LevelHeightAccessor$$Type, predicate9: $Predicate$$Type<$Holder$$Type<$Biome$$Type>>): $StructureStart
public "getModifiedStructureSettings"(): $Structure$StructureSettings
public "modifiableStructureInfo"(): $ModifiableStructureInfo
public static "settingsCodec"<S extends $Structure>(instance0: $RecordCodecBuilder$Instance$$Type<S>): $RecordCodecBuilder<S, $Structure$StructureSettings>
public static "simpleCodec"<S extends $Structure>(function0: $Function$$Type<$Structure$StructureSettings$$Type, S>): $Codec<S>
public "spawnOverrides"(): $Map<$MobCategory, $StructureSpawnOverride>
public "step"(): $GenerationStep$Decoration
public "terrainAdaptation"(): $TerrainAdjustment
public "type"(): $StructureType<any>
get "modifiedStructureSettings"(): $Structure$StructureSettings
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructure
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructureTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Structure$$Type = ($Structure | Special.WorldgenStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.StructureType" {
import { $RuinedPortalStructure } from "net.minecraft.world.level.levelgen.structure.structures.RuinedPortalStructure"
import { $OceanRuinStructure } from "net.minecraft.world.level.levelgen.structure.structures.OceanRuinStructure"
import { $WoodlandMansionStructure } from "net.minecraft.world.level.levelgen.structure.structures.WoodlandMansionStructure"
import { $EndCityStructure } from "net.minecraft.world.level.levelgen.structure.structures.EndCityStructure"
import { $IglooStructure } from "net.minecraft.world.level.levelgen.structure.structures.IglooStructure"
import { $SwampHutStructure } from "net.minecraft.world.level.levelgen.structure.structures.SwampHutStructure"
import { $MineshaftStructure } from "net.minecraft.world.level.levelgen.structure.structures.MineshaftStructure"
import { $ShipwreckStructure } from "net.minecraft.world.level.levelgen.structure.structures.ShipwreckStructure"
import { $DesertPyramidStructure } from "net.minecraft.world.level.levelgen.structure.structures.DesertPyramidStructure"
import { $StrongholdStructure } from "net.minecraft.world.level.levelgen.structure.structures.StrongholdStructure"
import { $Structure, $Structure$$Type } from "net.minecraft.world.level.levelgen.structure.Structure"
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $BuriedTreasureStructure } from "net.minecraft.world.level.levelgen.structure.structures.BuriedTreasureStructure"
import { $JigsawStructure } from "net.minecraft.world.level.levelgen.structure.structures.JigsawStructure"
import { $JungleTempleStructure } from "net.minecraft.world.level.levelgen.structure.structures.JungleTempleStructure"
import { $OceanMonumentStructure } from "net.minecraft.world.level.levelgen.structure.structures.OceanMonumentStructure"
import { $NetherFortressStructure } from "net.minecraft.world.level.levelgen.structure.structures.NetherFortressStructure"
import { $NetherFossilStructure } from "net.minecraft.world.level.levelgen.structure.structures.NetherFossilStructure"

export interface $StructureType<S extends $Structure = $Structure> {
"codec"(): $Codec<S>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructureType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructureTypeTag
}

export namespace $StructureType {
const BURIED_TREASURE: $StructureType<$BuriedTreasureStructure>
const DESERT_PYRAMID: $StructureType<$DesertPyramidStructure>
const END_CITY: $StructureType<$EndCityStructure>
const FORTRESS: $StructureType<$NetherFortressStructure>
const IGLOO: $StructureType<$IglooStructure>
const JIGSAW: $StructureType<$JigsawStructure>
const JUNGLE_TEMPLE: $StructureType<$JungleTempleStructure>
const MINESHAFT: $StructureType<$MineshaftStructure>
const NETHER_FOSSIL: $StructureType<$NetherFossilStructure>
const OCEAN_MONUMENT: $StructureType<$OceanMonumentStructure>
const OCEAN_RUIN: $StructureType<$OceanRuinStructure>
const RUINED_PORTAL: $StructureType<$RuinedPortalStructure>
const SHIPWRECK: $StructureType<$ShipwreckStructure>
const STRONGHOLD: $StructureType<$StrongholdStructure>
const SWAMP_HUT: $StructureType<$SwampHutStructure>
const WOODLAND_MANSION: $StructureType<$WoodlandMansionStructure>
function register<S extends $Structure>(string0: string, codec1: $Codec$$Type<S>): $StructureType<S>
}
export abstract class $StructureType$$Static<S extends $Structure = $Structure> implements $StructureType<S> {
static readonly "BURIED_TREASURE": $StructureType<$BuriedTreasureStructure>
static readonly "DESERT_PYRAMID": $StructureType<$DesertPyramidStructure>
static readonly "END_CITY": $StructureType<$EndCityStructure>
static readonly "FORTRESS": $StructureType<$NetherFortressStructure>
static readonly "IGLOO": $StructureType<$IglooStructure>
static readonly "JIGSAW": $StructureType<$JigsawStructure>
static readonly "JUNGLE_TEMPLE": $StructureType<$JungleTempleStructure>
static readonly "MINESHAFT": $StructureType<$MineshaftStructure>
static readonly "NETHER_FOSSIL": $StructureType<$NetherFossilStructure>
static readonly "OCEAN_MONUMENT": $StructureType<$OceanMonumentStructure>
static readonly "OCEAN_RUIN": $StructureType<$OceanRuinStructure>
static readonly "RUINED_PORTAL": $StructureType<$RuinedPortalStructure>
static readonly "SHIPWRECK": $StructureType<$ShipwreckStructure>
static readonly "STRONGHOLD": $StructureType<$StrongholdStructure>
static readonly "SWAMP_HUT": $StructureType<$SwampHutStructure>
static readonly "WOODLAND_MANSION": $StructureType<$WoodlandMansionStructure>

static "register"<S extends $Structure>(string0: string, codec1: $Codec$$Type<S>): $StructureType<S>
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureType$$Type<S extends $Structure = $Structure> = ($StructureType<S> | Special.WorldgenStructureType | (() => $Codec$$Type<S>));
}

declare module "net.minecraft.world.level.levelgen.structure.structures.SwampHutStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SwampHutStructure$$Type = ($SwampHutStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.RandomBlockMatchTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RandomBlockMatchTest$$Type = ($RandomBlockMatchTest);
}

declare module "net.minecraft.world.level.levelgen.structure.StructureSet" {
import { $Structure$$Type } from "net.minecraft.world.level.levelgen.structure.Structure"
import { $List, $List$$Type } from "java.util.List"
import { $StructureSet$StructureSelectionEntry, $StructureSet$StructureSelectionEntry$$Type } from "net.minecraft.world.level.levelgen.structure.StructureSet$StructureSelectionEntry"
import { $Codec } from "com.mojang.serialization.Codec"
import { $Holder, $Holder$$Type } from "net.minecraft.core.Holder"
import { $StructurePlacement, $StructurePlacement$$Type } from "net.minecraft.world.level.levelgen.structure.placement.StructurePlacement"
import { $Record } from "java.lang.Record"

export class $StructureSet extends $Record {
static readonly "CODEC": $Codec<$Holder<$StructureSet>>
static readonly "DIRECT_CODEC": $Codec<$StructureSet>

constructor(list0: $List$$Type<$StructureSet$StructureSelectionEntry$$Type>, structurePlacement1: $StructurePlacement$$Type)
constructor(holder0: $Holder$$Type<$Structure$$Type>, structurePlacement1: $StructurePlacement$$Type)

public static "entry"(holder0: $Holder$$Type<$Structure$$Type>, int1: integer): $StructureSet$StructureSelectionEntry
public static "entry"(holder0: $Holder$$Type<$Structure$$Type>): $StructureSet$StructureSelectionEntry
public "placement"(): $StructurePlacement
public "structures"(): $List<$StructureSet$StructureSelectionEntry>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructureSet
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructureSetTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureSet$$Type = ($StructureSet | Special.WorldgenStructureSet);
}

declare module "net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PiecesContainer$$Type = ($PiecesContainer);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.EndCityStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $EndCityStructure$$Type = ($EndCityStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.pools.StructureTemplatePool" {
import { $StructureTemplatePoolAccessor } from "gg.moonflower.etched.core.mixin.StructureTemplatePoolAccessor"
import { $ObjectArrayList, $ObjectArrayList$$Type } from "it.unimi.dsi.fastutil.objects.ObjectArrayList"
import { $RandomSource$$Type } from "net.minecraft.util.RandomSource"
import { $Function$$Type } from "java.util.function.Function"
import { $Pair, $Pair$$Type } from "com.mojang.datafixers.util.Pair"
import { $StructurePoolAccessor } from "com.finndog.moogs_structures.mixins.structures.StructurePoolAccessor"
import { $StructureTemplatePoolAccessor as $StructureTemplatePoolAccessor$0 } from "com.github.L_Ender.cataclysm.mixin.accessor.StructureTemplatePoolAccessor"
import { $List, $List$$Type } from "java.util.List"
import { $Codec } from "com.mojang.serialization.Codec"
import { $Holder, $Holder$$Type } from "net.minecraft.core.Holder"
import { $StructureTemplateManager$$Type } from "net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager"
import { $StructurePoolAccessor as $StructurePoolAccessor$0 } from "com.finndog.mes.mixins.structures.StructurePoolAccessor"
import { $StructureTemplatePool$Projection$$Type } from "net.minecraft.world.level.levelgen.structure.pools.StructureTemplatePool$Projection"
import { $StructurePoolAccessor as $StructurePoolAccessor$1 } from "com.craisinlord.integrated_api.mixins.structures.StructurePoolAccessor"
import { $AccessorStructureTemplatePool } from "net.darkhax.bookshelf.mixin.accessors.world.AccessorStructureTemplatePool"
import { $StructurePoolElement, $StructurePoolElement$$Type } from "net.minecraft.world.level.levelgen.structure.pools.StructurePoolElement"

export class $StructureTemplatePool implements $StructurePoolAccessor$1, $StructureTemplatePoolAccessor, $AccessorStructureTemplatePool, $StructureTemplatePoolAccessor$0, $StructurePoolAccessor, $StructurePoolAccessor$0 {
static readonly "CODEC": $Codec<$Holder<$StructureTemplatePool>>
static readonly "DIRECT_CODEC": $Codec<$StructureTemplatePool>

constructor(holder0: $Holder$$Type<$StructureTemplatePool$$Type>, list1: $List$$Type<$Pair$$Type<$StructurePoolElement$$Type, integer>>)
constructor(holder0: $Holder$$Type<$StructureTemplatePool$$Type>, list1: $List$$Type<$Pair$$Type<$Function$$Type<$StructureTemplatePool$Projection$$Type, $StructurePoolElement$$Type>, integer>>, projection2: $StructureTemplatePool$Projection$$Type)

public "getFallback"(): $Holder<$StructureTemplatePool>
public "getMaxSize"(structureTemplateManager0: $StructureTemplateManager$$Type): integer
public "getRandomTemplate"(randomSource0: $RandomSource$$Type): $StructurePoolElement
public "getShuffledTemplates"(randomSource0: $RandomSource$$Type): $List<$StructurePoolElement>
public "size"(): integer
get "rawTemplates"(): $List<$Pair<$StructurePoolElement, integer>>
set "rawTemplates"(value: $List$$Type<$Pair$$Type<$StructurePoolElement$$Type, integer>>)
get "templates"(): $ObjectArrayList<$StructurePoolElement>
set "templates"(value: $ObjectArrayList$$Type<$StructurePoolElement$$Type>)
get "fallback"(): $Holder<$StructureTemplatePool>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenTemplatePool
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenTemplatePoolTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureTemplatePool$$Type = ($StructureTemplatePool | Special.WorldgenTemplatePool);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate$StructureBlockInfo" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureTemplate$StructureBlockInfo$$Type = ($StructureTemplate$StructureBlockInfo);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.AlwaysTrueTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AlwaysTrueTest$$Type = ($AlwaysTrueTest);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.NetherFossilStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $NetherFossilStructure$$Type = ($NetherFossilStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.PosRuleTestType" {
import { $PosRuleTest, $PosRuleTest$$Type } from "net.minecraft.world.level.levelgen.structure.templatesystem.PosRuleTest"
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $AxisAlignedLinearPosTest } from "net.minecraft.world.level.levelgen.structure.templatesystem.AxisAlignedLinearPosTest"
import { $PosAlwaysTrueTest } from "net.minecraft.world.level.levelgen.structure.templatesystem.PosAlwaysTrueTest"
import { $LinearPosTest } from "net.minecraft.world.level.levelgen.structure.templatesystem.LinearPosTest"

export interface $PosRuleTestType<P extends $PosRuleTest = $PosRuleTest> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.PosRuleTest
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.PosRuleTestTag
}

export namespace $PosRuleTestType {
const ALWAYS_TRUE_TEST: $PosRuleTestType<$PosAlwaysTrueTest>
const AXIS_ALIGNED_LINEAR_POS_TEST: $PosRuleTestType<$AxisAlignedLinearPosTest>
const LINEAR_POS_TEST: $PosRuleTestType<$LinearPosTest>
function register<P extends $PosRuleTest>(string0: string, codec1: $Codec$$Type<P>): $PosRuleTestType<P>
}
export abstract class $PosRuleTestType$$Static<P extends $PosRuleTest = $PosRuleTest> implements $PosRuleTestType<P> {
static readonly "ALWAYS_TRUE_TEST": $PosRuleTestType<$PosAlwaysTrueTest>
static readonly "AXIS_ALIGNED_LINEAR_POS_TEST": $PosRuleTestType<$AxisAlignedLinearPosTest>
static readonly "LINEAR_POS_TEST": $PosRuleTestType<$LinearPosTest>

static "register"<P extends $PosRuleTest>(string0: string, codec1: $Codec$$Type<P>): $PosRuleTestType<P>
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PosRuleTestType$$Type<P extends $PosRuleTest = $PosRuleTest> = ($PosRuleTestType<P> | Special.PosRuleTest | (() => $Codec$$Type<P>));
}

declare module "net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PoolElementStructurePiece$$Type = ($PoolElementStructurePiece);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.StructurePlaceSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePlaceSettings$$Type = ($StructurePlaceSettings);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.RandomBlockStateMatchTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RandomBlockStateMatchTest$$Type = ($RandomBlockStateMatchTest);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.StructureProcessorList" {
import { $List, $List$$Type } from "java.util.List"
import { $StructureProcessor, $StructureProcessor$$Type } from "net.minecraft.world.level.levelgen.structure.templatesystem.StructureProcessor"

export class $StructureProcessorList {
"list": $List<$StructureProcessor>

constructor(list0: $List$$Type<$StructureProcessor$$Type>)

public "list"(): $List<$StructureProcessor>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenProcessorList
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenProcessorListTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureProcessorList$$Type = ($StructureProcessorList | Special.WorldgenProcessorList);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.BlockAgeProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BlockAgeProcessor$$Type = ($BlockAgeProcessor);
}

declare module "net.minecraft.world.level.levelgen.structure.placement.RandomSpreadStructurePlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RandomSpreadStructurePlacement$$Type = ($RandomSpreadStructurePlacement);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.NopProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $NopProcessor$$Type = ($NopProcessor);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity.RuleBlockEntityModifierType" {
import { $Passthrough } from "net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity.Passthrough"
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $RuleBlockEntityModifier, $RuleBlockEntityModifier$$Type } from "net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity.RuleBlockEntityModifier"
import { $AppendStatic } from "net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity.AppendStatic"
import { $AppendLoot } from "net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity.AppendLoot"
import { $Clear } from "net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity.Clear"

export interface $RuleBlockEntityModifierType<P extends $RuleBlockEntityModifier = $RuleBlockEntityModifier> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.RuleBlockEntityModifier
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.RuleBlockEntityModifierTag
}

export namespace $RuleBlockEntityModifierType {
const APPEND_LOOT: $RuleBlockEntityModifierType<$AppendLoot>
const APPEND_STATIC: $RuleBlockEntityModifierType<$AppendStatic>
const CLEAR: $RuleBlockEntityModifierType<$Clear>
const PASSTHROUGH: $RuleBlockEntityModifierType<$Passthrough>
}
export abstract class $RuleBlockEntityModifierType$$Static<P extends $RuleBlockEntityModifier = $RuleBlockEntityModifier> implements $RuleBlockEntityModifierType<P> {
static readonly "APPEND_LOOT": $RuleBlockEntityModifierType<$AppendLoot>
static readonly "APPEND_STATIC": $RuleBlockEntityModifierType<$AppendStatic>
static readonly "CLEAR": $RuleBlockEntityModifierType<$Clear>
static readonly "PASSTHROUGH": $RuleBlockEntityModifierType<$Passthrough>

}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RuleBlockEntityModifierType$$Type<P extends $RuleBlockEntityModifier = $RuleBlockEntityModifier> = ($RuleBlockEntityModifierType<P> | Special.RuleBlockEntityModifier | (() => $Codec$$Type<P>));
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.BlockStateMatchTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BlockStateMatchTest$$Type = ($BlockStateMatchTest);
}

declare module "net.minecraft.world.level.levelgen.structure.pools.EmptyPoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $EmptyPoolElement$$Type = ($EmptyPoolElement);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity.AppendStatic" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AppendStatic$$Type = ($AppendStatic);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.AxisAlignedLinearPosTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AxisAlignedLinearPosTest$$Type = ($AxisAlignedLinearPosTest);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.BlackstoneReplaceProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BlackstoneReplaceProcessor$$Type = ($BlackstoneReplaceProcessor);
}

declare module "net.minecraft.world.level.levelgen.structure.Structure$GenerationStub" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Structure$GenerationStub$$Type = ($Structure$GenerationStub);
}

declare module "net.minecraft.world.level.levelgen.structure.placement.StructurePlacement$ExclusionZone" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePlacement$ExclusionZone$$Type = ($StructurePlacement$ExclusionZone);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.OceanRuinStructure$Type" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $OceanRuinStructure$Type$$Type = ($OceanRuinStructure$Type | ("warm" | "cold"));
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.ProcessorRule" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ProcessorRule$$Type = ($ProcessorRule);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.JungleTempleStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $JungleTempleStructure$$Type = ($JungleTempleStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.pools.StructurePoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePoolElement$$Type = ($StructurePoolElement);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.RuinedPortalStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RuinedPortalStructure$$Type = ($RuinedPortalStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity.Clear" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Clear$$Type = ($Clear);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.RuinedPortalStructure$Setup" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RuinedPortalStructure$Setup$$Type = ($RuinedPortalStructure$Setup);
}

declare module "net.minecraft.world.level.levelgen.structure.StructurePieceAccessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePieceAccessor$$Type = ($StructurePieceAccessor);
}

declare module "net.minecraft.world.level.levelgen.structure.pools.ListPoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ListPoolElement$$Type = ($ListPoolElement);
}

declare module "net.minecraft.world.level.levelgen.structure.placement.ConcentricRingsStructurePlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ConcentricRingsStructurePlacement$$Type = ($ConcentricRingsStructurePlacement);
}

declare module "net.minecraft.world.level.levelgen.structure.StructureSet$StructureSelectionEntry" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureSet$StructureSelectionEntry$$Type = ($StructureSet$StructureSelectionEntry);
}

declare module "net.minecraft.world.level.levelgen.structure.BoundingBox" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BoundingBox$$Type = ($BoundingBox);
}

declare module "net.minecraft.world.level.levelgen.structure.placement.StructurePlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePlacement$$Type = ($StructurePlacement);
}

declare module "net.minecraft.world.level.levelgen.structure.Structure$StructureSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Structure$StructureSettings$$Type = ($Structure$StructureSettings);
}

declare module "net.minecraft.world.level.levelgen.structure.StructureCheck" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureCheck$$Type = ($StructureCheck);
}

declare module "net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SinglePoolElement$$Type = ($SinglePoolElement);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.RuleTest" {
import { $CompoundTag$$Type } from "net.minecraft.nbt.CompoundTag"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RuleTest$$Type = ($RuleTest | $CompoundTag$$Type);
}

declare module "net.minecraft.world.level.levelgen.structure.TerrainAdjustment" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $TerrainAdjustment$$Type = ($TerrainAdjustment | ("none" | "bury" | "beard_thin" | "beard_box"));
}

declare module "net.minecraft.world.level.levelgen.structure.placement.RandomSpreadType" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RandomSpreadType$$Type = ($RandomSpreadType | ("linear" | "triangular"));
}

declare module "net.minecraft.world.level.levelgen.structure.StructureSpawnOverride" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureSpawnOverride$$Type = ($StructureSpawnOverride);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate$StructureEntityInfo" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureTemplate$StructureEntityInfo$$Type = ($StructureTemplate$StructureEntityInfo);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate$Palette" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureTemplate$Palette$$Type = ($StructureTemplate$Palette);
}

declare module "net.minecraft.world.level.levelgen.structure.pieces.StructurePieceSerializationContext" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePieceSerializationContext$$Type = ($StructurePieceSerializationContext);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.MineshaftStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $MineshaftStructure$$Type = ($MineshaftStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.SinglePieceStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SinglePieceStructure$$Type = ($SinglePieceStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity.RuleBlockEntityModifier" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RuleBlockEntityModifier$$Type = ($RuleBlockEntityModifier);
}

declare module "net.minecraft.world.level.levelgen.structure.placement.StructurePlacementType" {
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $StructurePlacement, $StructurePlacement$$Type } from "net.minecraft.world.level.levelgen.structure.placement.StructurePlacement"
import { $ConcentricRingsStructurePlacement } from "net.minecraft.world.level.levelgen.structure.placement.ConcentricRingsStructurePlacement"
import { $RandomSpreadStructurePlacement } from "net.minecraft.world.level.levelgen.structure.placement.RandomSpreadStructurePlacement"

export interface $StructurePlacementType<SP extends $StructurePlacement = $StructurePlacement> {
"codec"(): $Codec<SP>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructurePlacement
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructurePlacementTag
}

export namespace $StructurePlacementType {
const CONCENTRIC_RINGS: $StructurePlacementType<$ConcentricRingsStructurePlacement>
const RANDOM_SPREAD: $StructurePlacementType<$RandomSpreadStructurePlacement>
}
export abstract class $StructurePlacementType$$Static<SP extends $StructurePlacement = $StructurePlacement> implements $StructurePlacementType<SP> {
static readonly "CONCENTRIC_RINGS": $StructurePlacementType<$ConcentricRingsStructurePlacement>
static readonly "RANDOM_SPREAD": $StructurePlacementType<$RandomSpreadStructurePlacement>

}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePlacementType$$Type<SP extends $StructurePlacement = $StructurePlacement> = ($StructurePlacementType<SP> | Special.WorldgenStructurePlacement | (() => $Codec$$Type<SP>));
}

declare module "net.minecraft.world.level.levelgen.structure.pieces.StructurePieceType" {
import { $CompoundTag, $CompoundTag$$Type } from "net.minecraft.nbt.CompoundTag"
import { $StructurePiece, $StructurePiece$$Type } from "net.minecraft.world.level.levelgen.structure.StructurePiece"
import { $StructurePieceSerializationContext, $StructurePieceSerializationContext$$Type } from "net.minecraft.world.level.levelgen.structure.pieces.StructurePieceSerializationContext"
import { $StructurePieceType$ContextlessType$$Type } from "net.minecraft.world.level.levelgen.structure.pieces.StructurePieceType$ContextlessType"

export interface $StructurePieceType {
"load"(structurePieceSerializationContext0: $StructurePieceSerializationContext$$Type, compoundTag1: $CompoundTag$$Type): $StructurePiece
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructurePiece
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructurePieceTag
}

export namespace $StructurePieceType {
const BURIED_TREASURE_PIECE: $StructurePieceType
const DESERT_PYRAMID_PIECE: $StructurePieceType
const END_CITY_PIECE: $StructurePieceType
const IGLOO: $StructurePieceType
const JIGSAW: $StructurePieceType
const JUNGLE_PYRAMID_PIECE: $StructurePieceType
const MINE_SHAFT_CORRIDOR: $StructurePieceType
const MINE_SHAFT_CROSSING: $StructurePieceType
const MINE_SHAFT_ROOM: $StructurePieceType
const MINE_SHAFT_STAIRS: $StructurePieceType
const NETHER_FORTRESS_BRIDGE_CROSSING: $StructurePieceType
const NETHER_FORTRESS_BRIDGE_END_FILLER: $StructurePieceType
const NETHER_FORTRESS_BRIDGE_STRAIGHT: $StructurePieceType
const NETHER_FORTRESS_CASTLE_CORRIDOR_STAIRS: $StructurePieceType
const NETHER_FORTRESS_CASTLE_CORRIDOR_T_BALCONY: $StructurePieceType
const NETHER_FORTRESS_CASTLE_ENTRANCE: $StructurePieceType
const NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR: $StructurePieceType
const NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_CROSSING: $StructurePieceType
const NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_LEFT_TURN: $StructurePieceType
const NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_RIGHT_TURN: $StructurePieceType
const NETHER_FORTRESS_CASTLE_STALK_ROOM: $StructurePieceType
const NETHER_FORTRESS_MONSTER_THRONE: $StructurePieceType
const NETHER_FORTRESS_ROOM_CROSSING: $StructurePieceType
const NETHER_FORTRESS_STAIRS_ROOM: $StructurePieceType
const NETHER_FORTRESS_START: $StructurePieceType
const NETHER_FOSSIL: $StructurePieceType
const OCEAN_MONUMENT_BUILDING: $StructurePieceType
const OCEAN_MONUMENT_CORE_ROOM: $StructurePieceType
const OCEAN_MONUMENT_DOUBLE_XY_ROOM: $StructurePieceType
const OCEAN_MONUMENT_DOUBLE_X_ROOM: $StructurePieceType
const OCEAN_MONUMENT_DOUBLE_YZ_ROOM: $StructurePieceType
const OCEAN_MONUMENT_DOUBLE_Y_ROOM: $StructurePieceType
const OCEAN_MONUMENT_DOUBLE_Z_ROOM: $StructurePieceType
const OCEAN_MONUMENT_ENTRY_ROOM: $StructurePieceType
const OCEAN_MONUMENT_PENTHOUSE: $StructurePieceType
const OCEAN_MONUMENT_SIMPLE_ROOM: $StructurePieceType
const OCEAN_MONUMENT_SIMPLE_TOP_ROOM: $StructurePieceType
const OCEAN_MONUMENT_WING_ROOM: $StructurePieceType
const OCEAN_RUIN: $StructurePieceType
const RUINED_PORTAL: $StructurePieceType
const SHIPWRECK_PIECE: $StructurePieceType
const STRONGHOLD_CHEST_CORRIDOR: $StructurePieceType
const STRONGHOLD_FILLER_CORRIDOR: $StructurePieceType
const STRONGHOLD_FIVE_CROSSING: $StructurePieceType
const STRONGHOLD_LEFT_TURN: $StructurePieceType
const STRONGHOLD_LIBRARY: $StructurePieceType
const STRONGHOLD_PORTAL_ROOM: $StructurePieceType
const STRONGHOLD_PRISON_HALL: $StructurePieceType
const STRONGHOLD_RIGHT_TURN: $StructurePieceType
const STRONGHOLD_ROOM_CROSSING: $StructurePieceType
const STRONGHOLD_STAIRS_DOWN: $StructurePieceType
const STRONGHOLD_START: $StructurePieceType
const STRONGHOLD_STRAIGHT: $StructurePieceType
const STRONGHOLD_STRAIGHT_STAIRS_DOWN: $StructurePieceType
const SWAMPLAND_HUT: $StructurePieceType
const WOODLAND_MANSION_PIECE: $StructurePieceType
function setPieceId(contextlessType0: $StructurePieceType$ContextlessType$$Type, string1: string): $StructurePieceType
}
export abstract class $StructurePieceType$$Static implements $StructurePieceType {
static readonly "BURIED_TREASURE_PIECE": $StructurePieceType
static readonly "DESERT_PYRAMID_PIECE": $StructurePieceType
static readonly "END_CITY_PIECE": $StructurePieceType
static readonly "IGLOO": $StructurePieceType
static readonly "JIGSAW": $StructurePieceType
static readonly "JUNGLE_PYRAMID_PIECE": $StructurePieceType
static readonly "MINE_SHAFT_CORRIDOR": $StructurePieceType
static readonly "MINE_SHAFT_CROSSING": $StructurePieceType
static readonly "MINE_SHAFT_ROOM": $StructurePieceType
static readonly "MINE_SHAFT_STAIRS": $StructurePieceType
static readonly "NETHER_FORTRESS_BRIDGE_CROSSING": $StructurePieceType
static readonly "NETHER_FORTRESS_BRIDGE_END_FILLER": $StructurePieceType
static readonly "NETHER_FORTRESS_BRIDGE_STRAIGHT": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_CORRIDOR_STAIRS": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_CORRIDOR_T_BALCONY": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_ENTRANCE": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_CROSSING": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_LEFT_TURN": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_RIGHT_TURN": $StructurePieceType
static readonly "NETHER_FORTRESS_CASTLE_STALK_ROOM": $StructurePieceType
static readonly "NETHER_FORTRESS_MONSTER_THRONE": $StructurePieceType
static readonly "NETHER_FORTRESS_ROOM_CROSSING": $StructurePieceType
static readonly "NETHER_FORTRESS_STAIRS_ROOM": $StructurePieceType
static readonly "NETHER_FORTRESS_START": $StructurePieceType
static readonly "NETHER_FOSSIL": $StructurePieceType
static readonly "OCEAN_MONUMENT_BUILDING": $StructurePieceType
static readonly "OCEAN_MONUMENT_CORE_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_DOUBLE_XY_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_DOUBLE_X_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_DOUBLE_YZ_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_DOUBLE_Y_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_DOUBLE_Z_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_ENTRY_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_PENTHOUSE": $StructurePieceType
static readonly "OCEAN_MONUMENT_SIMPLE_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_SIMPLE_TOP_ROOM": $StructurePieceType
static readonly "OCEAN_MONUMENT_WING_ROOM": $StructurePieceType
static readonly "OCEAN_RUIN": $StructurePieceType
static readonly "RUINED_PORTAL": $StructurePieceType
static readonly "SHIPWRECK_PIECE": $StructurePieceType
static readonly "STRONGHOLD_CHEST_CORRIDOR": $StructurePieceType
static readonly "STRONGHOLD_FILLER_CORRIDOR": $StructurePieceType
static readonly "STRONGHOLD_FIVE_CROSSING": $StructurePieceType
static readonly "STRONGHOLD_LEFT_TURN": $StructurePieceType
static readonly "STRONGHOLD_LIBRARY": $StructurePieceType
static readonly "STRONGHOLD_PORTAL_ROOM": $StructurePieceType
static readonly "STRONGHOLD_PRISON_HALL": $StructurePieceType
static readonly "STRONGHOLD_RIGHT_TURN": $StructurePieceType
static readonly "STRONGHOLD_ROOM_CROSSING": $StructurePieceType
static readonly "STRONGHOLD_STAIRS_DOWN": $StructurePieceType
static readonly "STRONGHOLD_START": $StructurePieceType
static readonly "STRONGHOLD_STRAIGHT": $StructurePieceType
static readonly "STRONGHOLD_STRAIGHT_STAIRS_DOWN": $StructurePieceType
static readonly "SWAMPLAND_HUT": $StructurePieceType
static readonly "WOODLAND_MANSION_PIECE": $StructurePieceType

static "setPieceId"(contextlessType0: $StructurePieceType$ContextlessType$$Type, string1: string): $StructurePieceType
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePieceType$$Type = ($StructurePieceType | Special.WorldgenStructurePiece | ((arg0: $StructurePieceSerializationContext, arg1: $CompoundTag) => $StructurePiece$$Type));
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.GravityProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $GravityProcessor$$Type = ($GravityProcessor);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.StrongholdStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StrongholdStructure$$Type = ($StrongholdStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.Structure$GenerationContext" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Structure$GenerationContext$$Type = ($Structure$GenerationContext);
}

declare module "net.minecraft.world.level.levelgen.structure.placement.StructurePlacement$FrequencyReductionMethod" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructurePlacement$FrequencyReductionMethod$$Type = ($StructurePlacement$FrequencyReductionMethod | ("default" | "legacy_type_1" | "legacy_type_2" | "legacy_type_3"));
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.StructureProcessorType" {
import { $BlockRotProcessor } from "net.minecraft.world.level.levelgen.structure.templatesystem.BlockRotProcessor"
import { $ProtectedBlockProcessor } from "net.minecraft.world.level.levelgen.structure.templatesystem.ProtectedBlockProcessor"
import { $StructureProcessor, $StructureProcessor$$Type } from "net.minecraft.world.level.levelgen.structure.templatesystem.StructureProcessor"
import { $CappedProcessor } from "net.minecraft.world.level.levelgen.structure.templatesystem.CappedProcessor"
import { $BlockIgnoreProcessor } from "net.minecraft.world.level.levelgen.structure.templatesystem.BlockIgnoreProcessor"
import { $NopProcessor } from "net.minecraft.world.level.levelgen.structure.templatesystem.NopProcessor"
import { $LavaSubmergedBlockProcessor } from "net.minecraft.world.level.levelgen.structure.templatesystem.LavaSubmergedBlockProcessor"
import { $BlockAgeProcessor } from "net.minecraft.world.level.levelgen.structure.templatesystem.BlockAgeProcessor"
import { $StructureProcessorList } from "net.minecraft.world.level.levelgen.structure.templatesystem.StructureProcessorList"
import { $BlackstoneReplaceProcessor } from "net.minecraft.world.level.levelgen.structure.templatesystem.BlackstoneReplaceProcessor"
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $Holder } from "net.minecraft.core.Holder"
import { $JigsawReplacementProcessor } from "net.minecraft.world.level.levelgen.structure.templatesystem.JigsawReplacementProcessor"
import { $GravityProcessor } from "net.minecraft.world.level.levelgen.structure.templatesystem.GravityProcessor"
import { $RuleProcessor } from "net.minecraft.world.level.levelgen.structure.templatesystem.RuleProcessor"

export interface $StructureProcessorType<P extends $StructureProcessor = $StructureProcessor> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenStructureProcessor
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenStructureProcessorTag
}

export namespace $StructureProcessorType {
const BLACKSTONE_REPLACE: $StructureProcessorType<$BlackstoneReplaceProcessor>
const BLOCK_AGE: $StructureProcessorType<$BlockAgeProcessor>
const BLOCK_IGNORE: $StructureProcessorType<$BlockIgnoreProcessor>
const BLOCK_ROT: $StructureProcessorType<$BlockRotProcessor>
const CAPPED: $StructureProcessorType<$CappedProcessor>
const DIRECT_CODEC: $Codec<$StructureProcessorList>
const GRAVITY: $StructureProcessorType<$GravityProcessor>
const JIGSAW_REPLACEMENT: $StructureProcessorType<$JigsawReplacementProcessor>
const LAVA_SUBMERGED_BLOCK: $StructureProcessorType<$LavaSubmergedBlockProcessor>
const LIST_CODEC: $Codec<$Holder<$StructureProcessorList>>
const LIST_OBJECT_CODEC: $Codec<$StructureProcessorList>
const NOP: $StructureProcessorType<$NopProcessor>
const PROTECTED_BLOCKS: $StructureProcessorType<$ProtectedBlockProcessor>
const RULE: $StructureProcessorType<$RuleProcessor>
const SINGLE_CODEC: $Codec<$StructureProcessor>
function register<P extends $StructureProcessor>(string0: string, codec1: $Codec$$Type<P>): $StructureProcessorType<P>
}
export abstract class $StructureProcessorType$$Static<P extends $StructureProcessor = $StructureProcessor> implements $StructureProcessorType<P> {
static readonly "BLACKSTONE_REPLACE": $StructureProcessorType<$BlackstoneReplaceProcessor>
static readonly "BLOCK_AGE": $StructureProcessorType<$BlockAgeProcessor>
static readonly "BLOCK_IGNORE": $StructureProcessorType<$BlockIgnoreProcessor>
static readonly "BLOCK_ROT": $StructureProcessorType<$BlockRotProcessor>
static readonly "CAPPED": $StructureProcessorType<$CappedProcessor>
static readonly "DIRECT_CODEC": $Codec<$StructureProcessorList>
static readonly "GRAVITY": $StructureProcessorType<$GravityProcessor>
static readonly "JIGSAW_REPLACEMENT": $StructureProcessorType<$JigsawReplacementProcessor>
static readonly "LAVA_SUBMERGED_BLOCK": $StructureProcessorType<$LavaSubmergedBlockProcessor>
static readonly "LIST_CODEC": $Codec<$Holder<$StructureProcessorList>>
static readonly "LIST_OBJECT_CODEC": $Codec<$StructureProcessorList>
static readonly "NOP": $StructureProcessorType<$NopProcessor>
static readonly "PROTECTED_BLOCKS": $StructureProcessorType<$ProtectedBlockProcessor>
static readonly "RULE": $StructureProcessorType<$RuleProcessor>
static readonly "SINGLE_CODEC": $Codec<$StructureProcessor>

static "register"<P extends $StructureProcessor>(string0: string, codec1: $Codec$$Type<P>): $StructureProcessorType<P>
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureProcessorType$$Type<P extends $StructureProcessor = $StructureProcessor> = ($StructureProcessorType<P> | Special.WorldgenStructureProcessor | (() => $Codec$$Type<P>));
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.BlockMatchTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BlockMatchTest$$Type = ($BlockMatchTest);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.ProtectedBlockProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ProtectedBlockProcessor$$Type = ($ProtectedBlockProcessor);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.JigsawStructure" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $JigsawStructure$$Type = ($JigsawStructure);
}

declare module "net.minecraft.world.level.levelgen.structure.structures.RuinedPortalPiece$VerticalPlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RuinedPortalPiece$VerticalPlacement$$Type = ($RuinedPortalPiece$VerticalPlacement | ("on_land_surface" | "partly_buried" | "on_ocean_floor" | "in_mountain" | "underground" | "in_nether"));
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureTemplate$$Type = ($StructureTemplate);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.StructureProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructureProcessor$$Type = ($StructureProcessor);
}

declare module "net.minecraft.world.level.levelgen.structure.templatesystem.RuleProcessor" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RuleProcessor$$Type = ($RuleProcessor);
}

