declare module "net.minecraft.world.entity.decoration.PaintingVariant" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
export class $PaintingVariant {
constructor(int0: integer, int1: integer)

public "getHeight"(): integer
public "getWidth"(): integer
get "height"(): integer
get "width"(): integer
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.PaintingVariant
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.PaintingVariantTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PaintingVariant$$Type = ($PaintingVariant | Special.PaintingVariant);
}

declare module "net.minecraft.world.entity.decoration.HangingEntity" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $HangingEntity$$Type = ($HangingEntity);
}

declare module "net.minecraft.world.entity.decoration.LeashFenceKnotEntity" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LeashFenceKnotEntity$$Type = ($LeashFenceKnotEntity);
}

declare module "net.minecraft.world.entity.decoration.Painting" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Painting$$Type = ($Painting);
}

declare module "net.minecraft.world.entity.decoration.ArmorStand" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ArmorStand$$Type = ($ArmorStand);
}

declare module "net.minecraft.world.entity.decoration.GlowItemFrame" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $GlowItemFrame$$Type = ($GlowItemFrame);
}

declare module "net.minecraft.world.entity.decoration.ItemFrame" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ItemFrame$$Type = ($ItemFrame);
}

