declare module "net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix$Conversion" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StructuresBecomeConfiguredFix$Conversion$$Type = ($StructuresBecomeConfiguredFix$Conversion);
}

declare module "net.minecraft.util.Tuple" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Tuple$$Type<A = any, B = any> = ($Tuple<A, B>);
}

declare module "net.minecraft.util.TaskChainer$DelayedTask" {
import { $Executor } from "java.util.concurrent.Executor"
import { $CompletableFuture$$Type } from "java.util.concurrent.CompletableFuture"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $TaskChainer$DelayedTask$$Type = ($TaskChainer$DelayedTask | ((arg0: $Executor) => $CompletableFuture$$Type<any>));
}

declare module "net.minecraft.util.StringRepresentable$EnumCodec" {
import { $Enum, $Enum$$Type } from "java.lang.Enum"
import { $StringRepresentable, $StringRepresentable$$Type } from "net.minecraft.util.StringRepresentable"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StringRepresentable$EnumCodec$$Type<E extends ($Enum<E> & $StringRepresentable) = ($Enum<E> & $StringRepresentable)> = ($StringRepresentable$EnumCodec<E>);
}

declare module "net.minecraft.util.profiling.metrics.MetricSampler$MetricSamplerBuilder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $MetricSampler$MetricSamplerBuilder$$Type<T = any> = ($MetricSampler$MetricSamplerBuilder<T>);
}

declare module "net.minecraft.util.BitStorage" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BitStorage$$Type = ($BitStorage);
}

declare module "net.minecraft.util.random.Weight" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Weight$$Type = ($Weight);
}

declare module "net.minecraft.util.valueproviders.ClampedInt" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ClampedInt$$Type = ($ClampedInt);
}

declare module "net.minecraft.util.valueproviders.UniformFloat" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $UniformFloat$$Type = ($UniformFloat);
}

declare module "net.minecraft.util.TimeSource" {
import { $TimeUnit } from "java.util.concurrent.TimeUnit"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $TimeSource$$Type = ($TimeSource | ((arg0: $TimeUnit) => long));
}

declare module "net.minecraft.util.random.WeightedEntry$Wrapper" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WeightedEntry$Wrapper$$Type<T = any> = ($WeightedEntry$Wrapper<T>);
}

declare module "net.minecraft.util.profiling.metrics.MetricSampler" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $MetricSampler$$Type = ($MetricSampler);
}

declare module "net.minecraft.util.valueproviders.FloatProviderType" {
import { $ClampedNormalFloat } from "net.minecraft.util.valueproviders.ClampedNormalFloat"
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $FloatProvider, $FloatProvider$$Type } from "net.minecraft.util.valueproviders.FloatProvider"
import { $ConstantFloat } from "net.minecraft.util.valueproviders.ConstantFloat"
import { $UniformFloat } from "net.minecraft.util.valueproviders.UniformFloat"
import { $TrapezoidFloat } from "net.minecraft.util.valueproviders.TrapezoidFloat"

export interface $FloatProviderType<P extends $FloatProvider = $FloatProvider> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.FloatProviderType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.FloatProviderTypeTag
}

export namespace $FloatProviderType {
const CLAMPED_NORMAL: $FloatProviderType<$ClampedNormalFloat>
const CONSTANT: $FloatProviderType<$ConstantFloat>
const TRAPEZOID: $FloatProviderType<$TrapezoidFloat>
const UNIFORM: $FloatProviderType<$UniformFloat>
function register<P extends $FloatProvider>(string0: string, codec1: $Codec$$Type<P>): $FloatProviderType<P>
}
export abstract class $FloatProviderType$$Static<P extends $FloatProvider = $FloatProvider> implements $FloatProviderType<P> {
static readonly "CLAMPED_NORMAL": $FloatProviderType<$ClampedNormalFloat>
static readonly "CONSTANT": $FloatProviderType<$ConstantFloat>
static readonly "TRAPEZOID": $FloatProviderType<$TrapezoidFloat>
static readonly "UNIFORM": $FloatProviderType<$UniformFloat>

static "register"<P extends $FloatProvider>(string0: string, codec1: $Codec$$Type<P>): $FloatProviderType<P>
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $FloatProviderType$$Type<P extends $FloatProvider = $FloatProvider> = ($FloatProviderType<P> | Special.FloatProviderType | (() => $Codec$$Type<P>));
}

declare module "net.minecraft.util.RandomSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RandomSource$$Type = ($RandomSource);
}

declare module "net.minecraft.util.TaskChainer" {
import { $TaskChainer$DelayedTask } from "net.minecraft.util.TaskChainer$DelayedTask"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $TaskChainer$$Type = ($TaskChainer | ((arg0: $TaskChainer$DelayedTask) => void));
}

declare module "net.minecraft.util.InclusiveRange" {
import { $Comparable, $Comparable$$Type } from "java.lang.Comparable"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $InclusiveRange$$Type<T extends $Comparable<T> = $Comparable<T>> = ($InclusiveRange<T>);
}

declare module "net.minecraft.util.thread.StrictQueue" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StrictQueue$$Type<T = any, F = any> = ($StrictQueue<T, F>);
}

declare module "net.minecraft.util.AbortableIterationConsumer" {
import { $AbortableIterationConsumer$Continuation$$Type } from "net.minecraft.util.AbortableIterationConsumer$Continuation"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AbortableIterationConsumer$$Type<T = any> = ($AbortableIterationConsumer<T> | ((arg0: T) => $AbortableIterationConsumer$Continuation$$Type));
}

declare module "net.minecraft.util.SignatureUpdater$Output" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SignatureUpdater$Output$$Type = ($SignatureUpdater$Output | ((arg0: byte[]) => void));
}

declare module "net.minecraft.util.ModCheck$Confidence" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ModCheck$Confidence$$Type = ($ModCheck$Confidence | ("probably_not" | "very_likely" | "definitely"));
}

declare module "net.minecraft.util.valueproviders.UniformInt" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $UniformInt$$Type = ($UniformInt);
}

declare module "net.minecraft.util.FormattedCharSequence" {
import { $FormattedCharSink } from "net.minecraft.util.FormattedCharSink"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $FormattedCharSequence$$Type = ($FormattedCharSequence | ((arg0: $FormattedCharSink) => boolean));
}

declare module "net.minecraft.util.LazyLoadedValue" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LazyLoadedValue$$Type<T = any> = ($LazyLoadedValue<T>);
}

declare module "net.minecraft.util.Unit" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Unit$$Type = ($Unit | ("instance"));
}

declare module "net.minecraft.util.random.WeightedRandomList" {
import { $WeightedEntry, $WeightedEntry$$Type } from "net.minecraft.util.random.WeightedEntry"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WeightedRandomList$$Type<E extends $WeightedEntry = $WeightedEntry> = ($WeightedRandomList<E>);
}

declare module "net.minecraft.util.valueproviders.IntProviderType" {
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $UniformInt } from "net.minecraft.util.valueproviders.UniformInt"
import { $IntProvider, $IntProvider$$Type } from "net.minecraft.util.valueproviders.IntProvider"
import { $ConstantInt } from "net.minecraft.util.valueproviders.ConstantInt"
import { $ClampedInt } from "net.minecraft.util.valueproviders.ClampedInt"
import { $ClampedNormalInt } from "net.minecraft.util.valueproviders.ClampedNormalInt"
import { $BiasedToBottomInt } from "net.minecraft.util.valueproviders.BiasedToBottomInt"
import { $WeightedListInt } from "net.minecraft.util.valueproviders.WeightedListInt"

export interface $IntProviderType<P extends $IntProvider = $IntProvider> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.IntProviderType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.IntProviderTypeTag
}

export namespace $IntProviderType {
const BIASED_TO_BOTTOM: $IntProviderType<$BiasedToBottomInt>
const CLAMPED: $IntProviderType<$ClampedInt>
const CLAMPED_NORMAL: $IntProviderType<$ClampedNormalInt>
const CONSTANT: $IntProviderType<$ConstantInt>
const UNIFORM: $IntProviderType<$UniformInt>
const WEIGHTED_LIST: $IntProviderType<$WeightedListInt>
function register<P extends $IntProvider>(string0: string, codec1: $Codec$$Type<P>): $IntProviderType<P>
}
export abstract class $IntProviderType$$Static<P extends $IntProvider = $IntProvider> implements $IntProviderType<P> {
static readonly "BIASED_TO_BOTTOM": $IntProviderType<$BiasedToBottomInt>
static readonly "CLAMPED": $IntProviderType<$ClampedInt>
static readonly "CLAMPED_NORMAL": $IntProviderType<$ClampedNormalInt>
static readonly "CONSTANT": $IntProviderType<$ConstantInt>
static readonly "UNIFORM": $IntProviderType<$UniformInt>
static readonly "WEIGHTED_LIST": $IntProviderType<$WeightedListInt>

static "register"<P extends $IntProvider>(string0: string, codec1: $Codec$$Type<P>): $IntProviderType<P>
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $IntProviderType$$Type<P extends $IntProvider = $IntProvider> = ($IntProviderType<P> | Special.IntProviderType | (() => $Codec$$Type<P>));
}

declare module "net.minecraft.util.thread.ReentrantBlockableEventLoop" {
import { $Runnable, $Runnable$$Type } from "java.lang.Runnable"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ReentrantBlockableEventLoop$$Type<R extends $Runnable = $Runnable> = ($ReentrantBlockableEventLoop<R>);
}

declare module "net.minecraft.util.thread.ProcessorHandle" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ProcessorHandle$$Type<Msg = any> = ($ProcessorHandle<Msg>);
}

declare module "net.minecraft.util.valueproviders.ClampedNormalInt" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ClampedNormalInt$$Type = ($ClampedNormalInt);
}

declare module "net.minecraft.util.random.WeightedEntry$IntrusiveBase" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WeightedEntry$IntrusiveBase$$Type = ($WeightedEntry$IntrusiveBase);
}

declare module "net.minecraft.util.profiling.ProfileResults" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ProfileResults$$Type = ($ProfileResults);
}

declare module "net.minecraft.util.profiling.ProfilerFiller" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ProfilerFiller$$Type = ($ProfilerFiller);
}

declare module "net.minecraft.util.valueproviders.TrapezoidFloat" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $TrapezoidFloat$$Type = ($TrapezoidFloat);
}

declare module "net.minecraft.util.SignatureUpdater" {
import { $SignatureUpdater$Output } from "net.minecraft.util.SignatureUpdater$Output"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SignatureUpdater$$Type = ($SignatureUpdater | ((arg0: $SignatureUpdater$Output) => void));
}

declare module "net.minecraft.util.valueproviders.ConstantFloat" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ConstantFloat$$Type = ($ConstantFloat);
}

declare module "net.minecraft.util.profiling.metrics.MetricCategory" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $MetricCategory$$Type = ($MetricCategory | ("path_finding" | "event_loops" | "mail_boxes" | "tick_loop" | "jvm" | "chunk_rendering" | "chunk_rendering_dispatching" | "cpu" | "gpu"));
}

declare module "net.minecraft.util.valueproviders.FloatProvider" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $FloatProvider$$Type = ($FloatProvider);
}

declare module "net.minecraft.util.KeyDispatchDataCodec" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $KeyDispatchDataCodec$$Type<A = any> = ($KeyDispatchDataCodec<A>);
}

declare module "net.minecraft.util.AbortableIterationConsumer$Continuation" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AbortableIterationConsumer$Continuation$$Type = ($AbortableIterationConsumer$Continuation | ("continue" | "abort"));
}

declare module "net.minecraft.util.FormattedCharSink" {
import { $Style } from "net.minecraft.network.chat.Style"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $FormattedCharSink$$Type = ($FormattedCharSink | ((arg0: integer, arg1: $Style, arg2: integer) => boolean));
}

declare module "net.minecraft.util.valueproviders.ConstantInt" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ConstantInt$$Type = ($ConstantInt);
}

declare module "net.minecraft.util.random.WeightedEntry" {
import { $Weight$$Type } from "net.minecraft.util.random.Weight"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WeightedEntry$$Type = ($WeightedEntry | (() => $Weight$$Type));
}

declare module "net.minecraft.util.OptionEnum" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $OptionEnum$$Type = ($OptionEnum);
}

declare module "net.minecraft.util.valueproviders.BiasedToBottomInt" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BiasedToBottomInt$$Type = ($BiasedToBottomInt);
}

declare module "net.minecraft.util.StringRepresentable" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StringRepresentable$$Type = ($StringRepresentable | (() => string));
}

declare module "net.minecraft.util.ProgressListener" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ProgressListener$$Type = ($ProgressListener);
}

declare module "net.minecraft.util.valueproviders.IntProvider" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $IntProvider$$Type = ($IntProvider);
}

declare module "net.minecraft.util.profiling.ResultField" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ResultField$$Type = ($ResultField);
}

declare module "net.minecraft.util.valueproviders.SampledFloat" {
import { $RandomSource } from "net.minecraft.util.RandomSource"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SampledFloat$$Type = ($SampledFloat | ((arg0: $RandomSource) => float));
}

declare module "net.minecraft.util.valueproviders.ClampedNormalFloat" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ClampedNormalFloat$$Type = ($ClampedNormalFloat);
}

declare module "net.minecraft.util.profiling.metrics.ProfilerMeasured" {
import { $List$$Type } from "java.util.List"
import { $MetricSampler$$Type } from "net.minecraft.util.profiling.metrics.MetricSampler"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ProfilerMeasured$$Type = ($ProfilerMeasured | (() => $List$$Type<$MetricSampler$$Type>));
}

declare module "net.minecraft.util.datafix.DataFixTypes" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DataFixTypes$$Type = ($DataFixTypes | ("level" | "player" | "chunk" | "hotbar" | "options" | "structure" | "stats" | "saved_data" | "advancements" | "poi_chunk" | "world_gen_settings" | "entity_chunk"));
}

declare module "net.minecraft.util.random.SimpleWeightedRandomList" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SimpleWeightedRandomList$$Type<E = any> = ($SimpleWeightedRandomList<E>);
}

declare module "net.minecraft.util.profiling.metrics.MetricSampler$SamplerResult" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $MetricSampler$SamplerResult$$Type = ($MetricSampler$SamplerResult);
}

declare module "net.minecraft.util.profiling.metrics.MetricSampler$ThresholdTest" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $MetricSampler$ThresholdTest$$Type = ($MetricSampler$ThresholdTest | ((arg0: double) => boolean));
}

declare module "net.minecraft.util.ClassInstanceMultiMap" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ClassInstanceMultiMap$$Type<T = any> = ($ClassInstanceMultiMap<T>);
}

declare module "net.minecraft.util.SignatureValidator" {
import { $SignatureUpdater } from "net.minecraft.util.SignatureUpdater"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SignatureValidator$$Type = ($SignatureValidator | ((arg0: $SignatureUpdater, arg1: byte[]) => boolean));
}

declare module "net.minecraft.util.random.SimpleWeightedRandomList$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SimpleWeightedRandomList$Builder$$Type<E = any> = ($SimpleWeightedRandomList$Builder<E>);
}

declare module "net.minecraft.util.FrameTimer" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $FrameTimer$$Type = ($FrameTimer);
}

declare module "net.minecraft.util.thread.ProcessorMailbox" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ProcessorMailbox$$Type<T = any> = ($ProcessorMailbox<T>);
}

declare module "net.minecraft.util.thread.BlockableEventLoop" {
import { $Runnable, $Runnable$$Type } from "java.lang.Runnable"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BlockableEventLoop$$Type<R extends $Runnable = $Runnable> = ($BlockableEventLoop<R>);
}

declare module "net.minecraft.util.ModCheck" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ModCheck$$Type = ($ModCheck);
}

declare module "net.minecraft.util.ExtraCodecs$TagOrElementLocation" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ExtraCodecs$TagOrElementLocation$$Type = ($ExtraCodecs$TagOrElementLocation);
}

declare module "net.minecraft.util.valueproviders.WeightedListInt" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WeightedListInt$$Type = ($WeightedListInt);
}

