declare module "net.minecraft.world.level.levelgen.carver.CarverDebugSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CarverDebugSettings$$Type = ($CarverDebugSettings);
}

declare module "net.minecraft.world.level.levelgen.carver.CanyonCarverConfiguration$CanyonShapeConfiguration" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CanyonCarverConfiguration$CanyonShapeConfiguration$$Type = ($CanyonCarverConfiguration$CanyonShapeConfiguration);
}

declare module "net.minecraft.world.level.levelgen.carver.NetherWorldCarver" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $NetherWorldCarver$$Type = ($NetherWorldCarver);
}

declare module "net.minecraft.world.level.levelgen.carver.WorldCarver" {
import { $CarverConfiguration, $CarverConfiguration$$Type } from "net.minecraft.world.level.levelgen.carver.CarverConfiguration"
import { $CaveCarverConfiguration } from "net.minecraft.world.level.levelgen.carver.CaveCarverConfiguration"
import { $CarvingContext$$Type } from "net.minecraft.world.level.levelgen.carver.CarvingContext"
import { $RandomSource$$Type } from "net.minecraft.util.RandomSource"
import { $CanyonCarverConfiguration } from "net.minecraft.world.level.levelgen.carver.CanyonCarverConfiguration"
import { $Function$$Type } from "java.util.function.Function"
import { $Biome } from "net.minecraft.world.level.biome.Biome"
import { $ChunkAccess$$Type } from "net.minecraft.world.level.chunk.ChunkAccess"
import { $CarvingMask$$Type } from "net.minecraft.world.level.chunk.CarvingMask"
import { $ChunkPos$$Type } from "net.minecraft.world.level.ChunkPos"
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $Holder } from "net.minecraft.core.Holder"
import { $BlockPos$$Type } from "net.minecraft.core.BlockPos"
import { $ConfiguredWorldCarver } from "net.minecraft.world.level.levelgen.carver.ConfiguredWorldCarver"
import { $Aquifer$$Type } from "net.minecraft.world.level.levelgen.Aquifer"

export class $WorldCarver<C extends $CarverConfiguration = $CarverConfiguration> {
static readonly "CANYON": $WorldCarver<$CanyonCarverConfiguration>
static readonly "CAVE": $WorldCarver<$CaveCarverConfiguration>
static readonly "NETHER_CAVE": $WorldCarver<$CaveCarverConfiguration>

constructor(codec0: $Codec$$Type<C>)

public "carve"(carvingContext0: $CarvingContext$$Type, c1: C, chunkAccess2: $ChunkAccess$$Type, function3: $Function$$Type<$BlockPos$$Type, $Holder<$Biome>>, randomSource4: $RandomSource$$Type, aquifer5: $Aquifer$$Type, chunkPos6: $ChunkPos$$Type, carvingMask7: $CarvingMask$$Type): boolean
public "configured"(c0: C): $ConfiguredWorldCarver<C>
public "configuredCodec"(): $Codec<$ConfiguredWorldCarver<C>>
public "getRange"(): integer
public "isStartChunk"(c0: C, randomSource1: $RandomSource$$Type): boolean
get "range"(): integer
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenCarver
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenCarverTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WorldCarver$$Type<C extends $CarverConfiguration = $CarverConfiguration> = ($WorldCarver<C> | Special.WorldgenCarver);
}

declare module "net.minecraft.world.level.levelgen.carver.CaveCarverConfiguration" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CaveCarverConfiguration$$Type = ($CaveCarverConfiguration);
}

declare module "net.minecraft.world.level.levelgen.carver.CaveWorldCarver" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CaveWorldCarver$$Type = ($CaveWorldCarver);
}

declare module "net.minecraft.world.level.levelgen.carver.CarvingContext" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CarvingContext$$Type = ($CarvingContext);
}

declare module "net.minecraft.world.level.levelgen.carver.CanyonCarverConfiguration" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CanyonCarverConfiguration$$Type = ($CanyonCarverConfiguration);
}

declare module "net.minecraft.world.level.levelgen.carver.CarverConfiguration" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CarverConfiguration$$Type = ($CarverConfiguration);
}

declare module "net.minecraft.world.level.levelgen.carver.ConfiguredWorldCarver" {
import { $CarverConfiguration, $CarverConfiguration$$Type } from "net.minecraft.world.level.levelgen.carver.CarverConfiguration"
import { $CarvingContext$$Type } from "net.minecraft.world.level.levelgen.carver.CarvingContext"
import { $HolderSet } from "net.minecraft.core.HolderSet"
import { $WorldCarver, $WorldCarver$$Type } from "net.minecraft.world.level.levelgen.carver.WorldCarver"
import { $RandomSource$$Type } from "net.minecraft.util.RandomSource"
import { $Record } from "java.lang.Record"
import { $Function$$Type } from "java.util.function.Function"
import { $Biome } from "net.minecraft.world.level.biome.Biome"
import { $ChunkAccess$$Type } from "net.minecraft.world.level.chunk.ChunkAccess"
import { $CarvingMask$$Type } from "net.minecraft.world.level.chunk.CarvingMask"
import { $ChunkPos$$Type } from "net.minecraft.world.level.ChunkPos"
import { $Codec } from "com.mojang.serialization.Codec"
import { $Holder } from "net.minecraft.core.Holder"
import { $BlockPos$$Type } from "net.minecraft.core.BlockPos"
import { $Aquifer$$Type } from "net.minecraft.world.level.levelgen.Aquifer"

export class $ConfiguredWorldCarver<WC extends $CarverConfiguration = $CarverConfiguration> extends $Record {
static readonly "CODEC": $Codec<$Holder<$ConfiguredWorldCarver<any>>>
static readonly "DIRECT_CODEC": $Codec<$ConfiguredWorldCarver<any>>
static readonly "LIST_CODEC": $Codec<$HolderSet<$ConfiguredWorldCarver<any>>>

constructor(worldCarver0: $WorldCarver$$Type<WC>, wc1: WC)

public "carve"(carvingContext0: $CarvingContext$$Type, chunkAccess1: $ChunkAccess$$Type, function2: $Function$$Type<$BlockPos$$Type, $Holder<$Biome>>, randomSource3: $RandomSource$$Type, aquifer4: $Aquifer$$Type, chunkPos5: $ChunkPos$$Type, carvingMask6: $CarvingMask$$Type): boolean
public "config"(): WC
public "isStartChunk"(randomSource0: $RandomSource$$Type): boolean
public "worldCarver"(): $WorldCarver<WC>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenConfiguredCarver
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenConfiguredCarverTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ConfiguredWorldCarver$$Type<WC extends $CarverConfiguration = $CarverConfiguration> = ($ConfiguredWorldCarver<WC> | Special.WorldgenConfiguredCarver);
}

declare module "net.minecraft.world.level.levelgen.carver.CanyonWorldCarver" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CanyonWorldCarver$$Type = ($CanyonWorldCarver);
}

