declare module "net.minecraft.world.entity.npc.VillagerProfession" {
import { $Holder, $Holder$$Type } from "net.minecraft.core.Holder"
import { $ImmutableSet, $ImmutableSet$$Type } from "com.google.common.collect.ImmutableSet"
import { $SoundEvent, $SoundEvent$$Type } from "net.minecraft.sounds.SoundEvent"
import { $Predicate, $Predicate$$Type } from "java.util.function.Predicate"
import { $Item, $Item$$Type } from "net.minecraft.world.item.Item"
import { $Block, $Block$$Type } from "net.minecraft.world.level.block.Block"
import { $Record } from "java.lang.Record"
import { $PoiType, $PoiType$$Type } from "net.minecraft.world.entity.ai.village.poi.PoiType"

export class $VillagerProfession extends $Record {
static readonly "ALL_ACQUIRABLE_JOBS": $Predicate<$Holder<$PoiType>>
static readonly "ARMORER": $VillagerProfession
static readonly "BUTCHER": $VillagerProfession
static readonly "CARTOGRAPHER": $VillagerProfession
static readonly "CLERIC": $VillagerProfession
static readonly "FARMER": $VillagerProfession
static readonly "FISHERMAN": $VillagerProfession
static readonly "FLETCHER": $VillagerProfession
static readonly "LEATHERWORKER": $VillagerProfession
static readonly "LIBRARIAN": $VillagerProfession
static readonly "MASON": $VillagerProfession
static readonly "NITWIT": $VillagerProfession
static readonly "NONE": $VillagerProfession
static readonly "SHEPHERD": $VillagerProfession
static readonly "TOOLSMITH": $VillagerProfession
static readonly "WEAPONSMITH": $VillagerProfession

constructor(string0: string, predicate1: $Predicate$$Type<$Holder$$Type<$PoiType$$Type>>, predicate2: $Predicate$$Type<$Holder$$Type<$PoiType$$Type>>, immutableSet3: $ImmutableSet$$Type<$Item$$Type>, immutableSet4: $ImmutableSet$$Type<$Block$$Type>, soundEvent5: $SoundEvent$$Type)

public "acquirableJobSite"(): $Predicate<$Holder<$PoiType>>
public "heldJobSite"(): $Predicate<$Holder<$PoiType>>
public "name"(): string
public "requestedItems"(): $ImmutableSet<$Item>
public "secondaryPoi"(): $ImmutableSet<$Block>
public "workSound"(): $SoundEvent
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.VillagerProfession
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.VillagerProfessionTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VillagerProfession$$Type = ($VillagerProfession | Special.VillagerProfession);
}

declare module "net.minecraft.world.entity.npc.InventoryCarrier" {
import { $SimpleContainer$$Type } from "net.minecraft.world.SimpleContainer"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $InventoryCarrier$$Type = ($InventoryCarrier | (() => $SimpleContainer$$Type));
}

declare module "net.minecraft.world.entity.npc.AbstractVillager" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AbstractVillager$$Type = ($AbstractVillager);
}

declare module "net.minecraft.world.entity.npc.VillagerType" {
import { $Holder$$Type } from "net.minecraft.core.Holder"
import { $Map } from "java.util.Map"
import { $ResourceKey, $ResourceKey$$Type } from "net.minecraft.resources.ResourceKey"
import { $Biome, $Biome$$Type } from "net.minecraft.world.level.biome.Biome"

export class $VillagerType {
static "BY_BIOME": $Map<$ResourceKey<$Biome>, $VillagerType>
static readonly "DESERT": $VillagerType
static readonly "JUNGLE": $VillagerType
static readonly "PLAINS": $VillagerType
static readonly "SAVANNA": $VillagerType
static readonly "SNOW": $VillagerType
static readonly "SWAMP": $VillagerType
static readonly "TAIGA": $VillagerType

constructor(string0: string)

public static "byBiome"(holder0: $Holder$$Type<$Biome$$Type>): $VillagerType
public static "registerBiomeType"(resourceKey0: $ResourceKey$$Type<$Biome>, villagerType1: $VillagerType$$Type): void
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.VillagerType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.VillagerTypeTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VillagerType$$Type = ($VillagerType | Special.VillagerType);
}

declare module "net.minecraft.world.entity.npc.Villager" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Villager$$Type = ($Villager);
}

declare module "net.minecraft.world.entity.npc.VillagerDataHolder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VillagerDataHolder$$Type = ($VillagerDataHolder);
}

declare module "net.minecraft.world.entity.npc.VillagerTrades$ItemListing" {
import { $Entity } from "net.minecraft.world.entity.Entity"
import { $MerchantOffer$$Type } from "net.minecraft.world.item.trading.MerchantOffer"
import { $RandomSource } from "net.minecraft.util.RandomSource"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VillagerTrades$ItemListing$$Type = ($VillagerTrades$ItemListing | ((arg0: $Entity, arg1: $RandomSource) => $MerchantOffer$$Type));
}

declare module "net.minecraft.world.entity.npc.Npc" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Npc$$Type = ($Npc);
}

declare module "net.minecraft.world.entity.npc.VillagerData" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VillagerData$$Type = ($VillagerData);
}

declare module "net.minecraft.world.entity.npc.WanderingTrader" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WanderingTrader$$Type = ($WanderingTrader);
}

