declare module "net.minecraft.world.level.gameevent.BlockPositionSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BlockPositionSource$$Type = ($BlockPositionSource);
}

declare module "net.minecraft.world.level.gameevent.GameEventListener" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $GameEventListener$$Type = ($GameEventListener);
}

declare module "net.minecraft.world.level.gameevent.PositionSourceType" {
import { $Codec } from "com.mojang.serialization.Codec"
import { $BlockPositionSource } from "net.minecraft.world.level.gameevent.BlockPositionSource"
import { $FriendlyByteBuf$$Type } from "net.minecraft.network.FriendlyByteBuf"
import { $EntityPositionSource } from "net.minecraft.world.level.gameevent.EntityPositionSource"
import { $PositionSource, $PositionSource$$Type } from "net.minecraft.world.level.gameevent.PositionSource"

export interface $PositionSourceType<T extends $PositionSource = $PositionSource> {
"codec"(): $Codec<T>
"read"(friendlyByteBuf0: $FriendlyByteBuf$$Type): T
"write"(friendlyByteBuf0: $FriendlyByteBuf$$Type, t1: T): void
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.PositionSourceType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.PositionSourceTypeTag
}

export namespace $PositionSourceType {
const BLOCK: $PositionSourceType<$BlockPositionSource>
const ENTITY: $PositionSourceType<$EntityPositionSource>
function fromNetwork(friendlyByteBuf0: $FriendlyByteBuf$$Type): $PositionSource
function register<S extends $PositionSourceType<T>, T extends $PositionSource>(string0: string, s1: S): S
function toNetwork<T extends $PositionSource>(t0: T, friendlyByteBuf1: $FriendlyByteBuf$$Type): void
}
export abstract class $PositionSourceType$$Static<T extends $PositionSource = $PositionSource> implements $PositionSourceType<T> {
static readonly "BLOCK": $PositionSourceType<$BlockPositionSource>
static readonly "ENTITY": $PositionSourceType<$EntityPositionSource>

static "fromNetwork"(friendlyByteBuf0: $FriendlyByteBuf$$Type): $PositionSource
static "register"<S extends $PositionSourceType<T>, T extends $PositionSource>(string0: string, s1: S): S
static "toNetwork"<T extends $PositionSource>(t0: T, friendlyByteBuf1: $FriendlyByteBuf$$Type): void
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PositionSourceType$$Type<T extends $PositionSource = $PositionSource> = ($PositionSourceType<T> | Special.PositionSourceType);
}

declare module "net.minecraft.world.level.gameevent.GameEventListener$DeliveryMode" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $GameEventListener$DeliveryMode$$Type = ($GameEventListener$DeliveryMode | ("unspecified" | "by_distance"));
}

declare module "net.minecraft.world.level.gameevent.vibrations.VibrationSystem$User" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VibrationSystem$User$$Type = ($VibrationSystem$User);
}

declare module "net.minecraft.world.level.gameevent.GameEventListener$Holder" {
import { $GameEventListener, $GameEventListener$$Type } from "net.minecraft.world.level.gameevent.GameEventListener"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $GameEventListener$Holder$$Type<T extends $GameEventListener = $GameEventListener> = ($GameEventListener$Holder<T> | (() => T));
}

declare module "net.minecraft.world.level.gameevent.vibrations.VibrationSystem" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VibrationSystem$$Type = ($VibrationSystem);
}

declare module "net.minecraft.world.level.gameevent.EntityPositionSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $EntityPositionSource$$Type = ($EntityPositionSource);
}

declare module "net.minecraft.world.level.gameevent.GameEvent$Context" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $GameEvent$Context$$Type = ($GameEvent$Context);
}

declare module "net.minecraft.world.level.gameevent.vibrations.VibrationSystem$Data" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VibrationSystem$Data$$Type = ($VibrationSystem$Data);
}

declare module "net.minecraft.world.level.gameevent.GameEvent" {
import { $ResourceLocation } from "net.minecraft.resources.ResourceLocation"
import { $TagKey$$Type } from "net.minecraft.tags.TagKey"
import { $InjectedGameEventExtension } from "dev.architectury.extensions.injected.InjectedGameEventExtension"
import { $Holder } from "net.minecraft.core.Holder"
import { $Holder$Reference } from "net.minecraft.core.Holder$Reference"

export class $GameEvent implements $InjectedGameEventExtension {
static readonly "BLOCK_ACTIVATE": $GameEvent
static readonly "BLOCK_ATTACH": $GameEvent
static readonly "BLOCK_CHANGE": $GameEvent
static readonly "BLOCK_CLOSE": $GameEvent
static readonly "BLOCK_DEACTIVATE": $GameEvent
static readonly "BLOCK_DESTROY": $GameEvent
static readonly "BLOCK_DETACH": $GameEvent
static readonly "BLOCK_OPEN": $GameEvent
static readonly "BLOCK_PLACE": $GameEvent
static readonly "CONTAINER_CLOSE": $GameEvent
static readonly "CONTAINER_OPEN": $GameEvent
static readonly "DEFAULT_NOTIFICATION_RADIUS": integer
static readonly "DRINK": $GameEvent
static readonly "EAT": $GameEvent
static readonly "ELYTRA_GLIDE": $GameEvent
static readonly "ENTITY_DAMAGE": $GameEvent
static readonly "ENTITY_DIE": $GameEvent
static readonly "ENTITY_DISMOUNT": $GameEvent
static readonly "ENTITY_INTERACT": $GameEvent
static readonly "ENTITY_MOUNT": $GameEvent
static readonly "ENTITY_PLACE": $GameEvent
static readonly "ENTITY_ROAR": $GameEvent
static readonly "ENTITY_SHAKE": $GameEvent
static readonly "EQUIP": $GameEvent
static readonly "EXPLODE": $GameEvent
static readonly "FLAP": $GameEvent
static readonly "FLUID_PICKUP": $GameEvent
static readonly "FLUID_PLACE": $GameEvent
static readonly "HIT_GROUND": $GameEvent
static readonly "INSTRUMENT_PLAY": $GameEvent
static readonly "ITEM_INTERACT_FINISH": $GameEvent
static readonly "ITEM_INTERACT_START": $GameEvent
static readonly "JUKEBOX_PLAY": $GameEvent
static readonly "JUKEBOX_STOP_PLAY": $GameEvent
static readonly "LIGHTNING_STRIKE": $GameEvent
static readonly "NOTE_BLOCK_PLAY": $GameEvent
static readonly "PRIME_FUSE": $GameEvent
static readonly "PROJECTILE_LAND": $GameEvent
static readonly "PROJECTILE_SHOOT": $GameEvent
static readonly "RESONATE_1": $GameEvent
static readonly "RESONATE_10": $GameEvent
static readonly "RESONATE_11": $GameEvent
static readonly "RESONATE_12": $GameEvent
static readonly "RESONATE_13": $GameEvent
static readonly "RESONATE_14": $GameEvent
static readonly "RESONATE_15": $GameEvent
static readonly "RESONATE_2": $GameEvent
static readonly "RESONATE_3": $GameEvent
static readonly "RESONATE_4": $GameEvent
static readonly "RESONATE_5": $GameEvent
static readonly "RESONATE_6": $GameEvent
static readonly "RESONATE_7": $GameEvent
static readonly "RESONATE_8": $GameEvent
static readonly "RESONATE_9": $GameEvent
static readonly "SCULK_SENSOR_TENDRILS_CLICKING": $GameEvent
static readonly "SHEAR": $GameEvent
static readonly "SHRIEK": $GameEvent
static readonly "SPLASH": $GameEvent
static readonly "STEP": $GameEvent
static readonly "SWIM": $GameEvent
static readonly "TELEPORT": $GameEvent

constructor(string0: string, int1: integer)

public "arch$holder"(): $Holder<$GameEvent>
public "arch$registryName"(): $ResourceLocation
/** @deprecated */
public "builtInRegistryHolder"(): $Holder$Reference<$GameEvent>
public "getName"(): string
public "getNotificationRadius"(): integer
public "is"(tagKey0: $TagKey$$Type<$GameEvent$$Type>): boolean
get "name"(): string
get "notificationRadius"(): integer
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.GameEvent
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.GameEventTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $GameEvent$$Type = ($GameEvent | Special.GameEvent);
}

declare module "net.minecraft.world.level.gameevent.DynamicGameEventListener" {
import { $GameEventListener, $GameEventListener$$Type } from "net.minecraft.world.level.gameevent.GameEventListener"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DynamicGameEventListener$$Type<T extends $GameEventListener = $GameEventListener> = ($DynamicGameEventListener<T>);
}

declare module "net.minecraft.world.level.gameevent.vibrations.VibrationInfo" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VibrationInfo$$Type = ($VibrationInfo);
}

declare module "net.minecraft.world.level.gameevent.PositionSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PositionSource$$Type = ($PositionSource);
}

declare module "net.minecraft.world.level.gameevent.vibrations.VibrationSelector" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VibrationSelector$$Type = ($VibrationSelector);
}

declare module "net.minecraft.world.level.gameevent.EntityPositionSource$Type" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $EntityPositionSource$Type$$Type = ($EntityPositionSource$Type);
}

declare module "net.minecraft.world.level.gameevent.BlockPositionSource$Type" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BlockPositionSource$Type$$Type = ($BlockPositionSource$Type);
}

declare module "net.minecraft.world.level.gameevent.vibrations.VibrationSystem$Listener" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $VibrationSystem$Listener$$Type = ($VibrationSystem$Listener);
}

