declare module "net.minecraft.world.effect.MobEffect" {
import { $AttributeModifier$Operation$$Type } from "net.minecraft.world.entity.ai.attributes.AttributeModifier$Operation"
import { $LivingEntity$$Type } from "net.minecraft.world.entity.LivingEntity"
import { $Component } from "net.minecraft.network.chat.Component"
import { $MobEffectInstance$$Type } from "net.minecraft.world.effect.MobEffectInstance"
import { $IForgeMobEffect } from "net.minecraftforge.common.extensions.IForgeMobEffect"
import { $MobEffectCategory } from "net.minecraft.world.effect.MobEffectCategory"
import { $Supplier$$Type } from "java.util.function.Supplier"
import { $Attribute, $Attribute$$Type } from "net.minecraft.world.entity.ai.attributes.Attribute"
import { $Consumer$$Type } from "java.util.function.Consumer"
import { $List } from "java.util.List"
import { $Entity$$Type } from "net.minecraft.world.entity.Entity"
import { $AttributeModifier, $AttributeModifier$$Type } from "net.minecraft.world.entity.ai.attributes.AttributeModifier"
import { $MobEffectInstance$FactorData } from "net.minecraft.world.effect.MobEffectInstance$FactorData"
import { $Map } from "java.util.Map"
import { $IClientMobEffectExtensions$$Type } from "net.minecraftforge.client.extensions.common.IClientMobEffectExtensions"
import { $Optional } from "java.util.Optional"
import { $ItemStack } from "net.minecraft.world.item.ItemStack"
import { $AttributeMap$$Type } from "net.minecraft.world.entity.ai.attributes.AttributeMap"

export class $MobEffect implements $IForgeMobEffect {
public "addAttributeModifier"(attribute0: $Attribute$$Type, string1: string, double2: double, operation3: $AttributeModifier$Operation$$Type): $MobEffect
public "addAttributeModifiers"(livingEntity0: $LivingEntity$$Type, attributeMap1: $AttributeMap$$Type, int2: integer): void
public "applyEffectTick"(livingEntity0: $LivingEntity$$Type, int1: integer): void
public "applyInstantenousEffect"(entity0: $Entity$$Type, entity1: $Entity$$Type, livingEntity2: $LivingEntity$$Type, int3: integer, double4: double): void
public static "byId"(int0: integer): $MobEffect
public "createFactorData"(): $Optional<$MobEffectInstance$FactorData>
public "getAttributeModifierValue"(int0: integer, attributeModifier1: $AttributeModifier$$Type): double
public "getAttributeModifiers"(): $Map<$Attribute, $AttributeModifier>
public "getCategory"(): $MobEffectCategory
public "getColor"(): integer
public "getCurativeItems"(): $List<$ItemStack>
public "getDescriptionId"(): string
public "getDisplayName"(): $Component
public "getEffectRendererInternal"(): any
public static "getId"(mobEffect0: $MobEffect$$Type): integer
public static "getIdFromNullable"(mobEffect0: $MobEffect$$Type): integer
public "getSortOrder"(mobEffectInstance0: $MobEffectInstance$$Type): integer
public "initializeClient"(consumer0: $Consumer$$Type<$IClientMobEffectExtensions$$Type>): void
public "isBeneficial"(): boolean
public "isDurationEffectTick"(int0: integer, int1: integer): boolean
public "isInstantenous"(): boolean
public "removeAttributeModifiers"(livingEntity0: $LivingEntity$$Type, attributeMap1: $AttributeMap$$Type, int2: integer): void
public "setFactorDataFactory"(supplier0: $Supplier$$Type<$MobEffectInstance$FactorData>): $MobEffect
get "attributeModifiers"(): $Map<$Attribute, $AttributeModifier>
get "category"(): $MobEffectCategory
get "color"(): integer
get "curativeItems"(): $List<$ItemStack>
get "descriptionId"(): string
get "displayName"(): $Component
get "effectRendererInternal"(): any
get "beneficial"(): boolean
get "instantenous"(): boolean
set "factorDataFactory"(value: $Supplier$$Type<$MobEffectInstance$FactorData>)
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.MobEffect
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.MobEffectTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $MobEffect$$Type = ($MobEffect | Special.MobEffect);
}

declare module "net.minecraft.world.effect.MobEffectInstance$FactorData" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $MobEffectInstance$FactorData$$Type = ($MobEffectInstance$FactorData);
}

declare module "net.minecraft.world.effect.AbsoptionMobEffect" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AbsoptionMobEffect$$Type = ($AbsoptionMobEffect);
}

declare module "net.minecraft.world.effect.MobEffectInstance" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $MobEffectInstance$$Type = ($MobEffectInstance);
}

declare module "net.minecraft.world.effect.MobEffectCategory" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $MobEffectCategory$$Type = ($MobEffectCategory | ("beneficial" | "harmful" | "neutral"));
}

declare module "net.minecraft.world.effect.InstantenousMobEffect" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $InstantenousMobEffect$$Type = ($InstantenousMobEffect);
}

declare module "net.minecraft.world.effect.HealthBoostMobEffect" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $HealthBoostMobEffect$$Type = ($HealthBoostMobEffect);
}

declare module "net.minecraft.world.effect.AttackDamageMobEffect" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AttackDamageMobEffect$$Type = ($AttackDamageMobEffect);
}

