declare module "net.minecraft.world.level.storage.loot.LootContext$VisitedEntry" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootContext$VisitedEntry$$Type<T = any> = ($LootContext$VisitedEntry<T>);
}

declare module "net.minecraft.world.level.storage.loot.functions.LootItemFunction" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootItemFunction$$Type = ($LootItemFunction);
}

declare module "net.minecraft.world.level.storage.loot.predicates.LootItemConditionType" {
import { $Serializer$$Type } from "net.minecraft.world.level.storage.loot.Serializer"
import { $LootItemCondition, $LootItemCondition$$Type } from "net.minecraft.world.level.storage.loot.predicates.LootItemCondition"
import { $SerializerType } from "net.minecraft.world.level.storage.loot.SerializerType"

export class $LootItemConditionType extends $SerializerType<$LootItemCondition> {
constructor(serializer0: $Serializer$$Type<$LootItemCondition$$Type>)

/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.LootConditionType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.LootConditionTypeTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootItemConditionType$$Type = ($LootItemConditionType | Special.LootConditionType);
}

declare module "net.minecraft.world.level.storage.loot.predicates.AnyOfCondition$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AnyOfCondition$Builder$$Type = ($AnyOfCondition$Builder);
}

declare module "net.minecraft.world.level.storage.LevelVersion" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LevelVersion$$Type = ($LevelVersion);
}

declare module "net.minecraft.world.level.storage.loot.providers.nbt.NbtProvider" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $NbtProvider$$Type = ($NbtProvider);
}

declare module "net.minecraft.world.level.storage.DataVersion" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DataVersion$$Type = ($DataVersion);
}

declare module "net.minecraft.world.level.storage.loot.providers.score.ScoreboardNameProvider" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ScoreboardNameProvider$$Type = ($ScoreboardNameProvider);
}

declare module "net.minecraft.world.level.storage.loot.predicates.LootItemCondition$Builder" {
import { $LootItemCondition$$Type } from "net.minecraft.world.level.storage.loot.predicates.LootItemCondition"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootItemCondition$Builder$$Type = ($LootItemCondition$Builder | (() => $LootItemCondition$$Type));
}

declare module "net.minecraft.world.level.storage.loot.entries.LootPoolEntryType" {
import { $Serializer$$Type } from "net.minecraft.world.level.storage.loot.Serializer"
import { $LootPoolEntryContainer, $LootPoolEntryContainer$$Type } from "net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer"
import { $SerializerType } from "net.minecraft.world.level.storage.loot.SerializerType"

export class $LootPoolEntryType extends $SerializerType<$LootPoolEntryContainer> {
constructor(serializer0: $Serializer$$Type<$LootPoolEntryContainer$$Type>)

/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.LootPoolEntryType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.LootPoolEntryTypeTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootPoolEntryType$$Type = ($LootPoolEntryType | Special.LootPoolEntryType);
}

declare module "net.minecraft.world.level.storage.LevelStorageSource$LevelCandidates" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LevelStorageSource$LevelCandidates$$Type = ($LevelStorageSource$LevelCandidates);
}

declare module "net.minecraft.world.level.storage.loot.LootDataType" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootDataType$$Type<T = any> = ($LootDataType<T>);
}

declare module "net.minecraft.world.level.storage.loot.LootParams$DynamicDrop" {
import { $Consumer } from "java.util.function.Consumer"
import { $ItemStack } from "net.minecraft.world.item.ItemStack"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootParams$DynamicDrop$$Type = ($LootParams$DynamicDrop | ((arg0: $Consumer<$ItemStack>) => void));
}

declare module "net.minecraft.world.level.storage.loot.entries.AlternativesEntry$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AlternativesEntry$Builder$$Type = ($AlternativesEntry$Builder);
}

declare module "net.minecraft.world.level.storage.loot.functions.LootItemFunctionType" {
import { $LootItemFunction, $LootItemFunction$$Type } from "net.minecraft.world.level.storage.loot.functions.LootItemFunction"
import { $Serializer$$Type } from "net.minecraft.world.level.storage.loot.Serializer"
import { $SerializerType } from "net.minecraft.world.level.storage.loot.SerializerType"

export class $LootItemFunctionType extends $SerializerType<$LootItemFunction> {
constructor(serializer0: $Serializer$$Type<$LootItemFunction$$Type>)

/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.LootFunctionType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.LootFunctionTypeTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootItemFunctionType$$Type = ($LootItemFunctionType | Special.LootFunctionType);
}

declare module "net.minecraft.world.level.storage.loot.LootPool" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootPool$$Type = ($LootPool);
}

declare module "net.minecraft.world.level.storage.loot.parameters.LootContextParams" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootContextParams$$Type = ($LootContextParams);
}

declare module "net.minecraft.world.level.storage.loot.predicates.CompositeLootItemCondition$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CompositeLootItemCondition$Builder$$Type = ($CompositeLootItemCondition$Builder);
}

declare module "net.minecraft.world.level.storage.loot.providers.number.NumberProvider" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $NumberProvider$$Type = ($NumberProvider);
}

declare module "net.minecraft.world.level.storage.loot.LootDataId" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootDataId$$Type<T = any> = ($LootDataId<T>);
}

declare module "net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LevelStorageSource$LevelStorageAccess$$Type = ($LevelStorageSource$LevelStorageAccess);
}

declare module "net.minecraft.world.level.storage.CommandStorage" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CommandStorage$$Type = ($CommandStorage);
}

declare module "net.minecraft.world.level.storage.loot.entries.ComposableEntryContainer" {
import { $Consumer } from "java.util.function.Consumer"
import { $LootPoolEntry } from "net.minecraft.world.level.storage.loot.entries.LootPoolEntry"
import { $LootContext } from "net.minecraft.world.level.storage.loot.LootContext"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ComposableEntryContainer$$Type = ($ComposableEntryContainer | ((arg0: $LootContext, arg1: $Consumer<$LootPoolEntry>) => boolean));
}

declare module "net.minecraft.world.level.storage.loot.entries.LootPoolEntry" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootPoolEntry$$Type = ($LootPoolEntry);
}

declare module "net.minecraft.world.level.storage.WritableLevelData" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WritableLevelData$$Type = ($WritableLevelData);
}

declare module "net.minecraft.world.level.storage.loot.LootContextUser" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootContextUser$$Type = ($LootContextUser);
}

declare module "net.minecraft.world.level.storage.loot.ValidationContext" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ValidationContext$$Type = ($ValidationContext);
}

declare module "net.minecraft.world.level.storage.loot.providers.score.LootScoreProviderType" {
import { $Serializer$$Type } from "net.minecraft.world.level.storage.loot.Serializer"
import { $ScoreboardNameProvider, $ScoreboardNameProvider$$Type } from "net.minecraft.world.level.storage.loot.providers.score.ScoreboardNameProvider"
import { $SerializerType } from "net.minecraft.world.level.storage.loot.SerializerType"

export class $LootScoreProviderType extends $SerializerType<$ScoreboardNameProvider> {
constructor(serializer0: $Serializer$$Type<$ScoreboardNameProvider$$Type>)

/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.LootScoreProviderType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.LootScoreProviderTypeTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootScoreProviderType$$Type = ($LootScoreProviderType | Special.LootScoreProviderType);
}

declare module "net.minecraft.world.level.storage.loot.providers.number.LootNumberProviderType" {
import { $NumberProvider, $NumberProvider$$Type } from "net.minecraft.world.level.storage.loot.providers.number.NumberProvider"
import { $Serializer$$Type } from "net.minecraft.world.level.storage.loot.Serializer"
import { $SerializerType } from "net.minecraft.world.level.storage.loot.SerializerType"

export class $LootNumberProviderType extends $SerializerType<$NumberProvider> {
constructor(serializer0: $Serializer$$Type<$NumberProvider$$Type>)

/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.LootNumberProviderType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.LootNumberProviderTypeTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootNumberProviderType$$Type = ($LootNumberProviderType | Special.LootNumberProviderType);
}

declare module "net.minecraft.world.level.storage.loot.parameters.LootContextParamSet" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootContextParamSet$$Type = ($LootContextParamSet);
}

declare module "net.minecraft.world.level.storage.loot.SerializerType" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SerializerType$$Type<T = any> = ($SerializerType<T>);
}

declare module "net.minecraft.world.level.storage.loot.LootTable$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootTable$Builder$$Type = ($LootTable$Builder);
}

declare module "net.minecraft.world.level.storage.ServerLevelData" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ServerLevelData$$Type = ($ServerLevelData);
}

declare module "net.minecraft.world.level.storage.DimensionDataStorage" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $DimensionDataStorage$$Type = ($DimensionDataStorage);
}

declare module "net.minecraft.world.level.storage.LevelResource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LevelResource$$Type = ($LevelResource);
}

declare module "net.minecraft.world.level.storage.loot.providers.nbt.LootNbtProviderType" {
import { $Serializer$$Type } from "net.minecraft.world.level.storage.loot.Serializer"
import { $NbtProvider, $NbtProvider$$Type } from "net.minecraft.world.level.storage.loot.providers.nbt.NbtProvider"
import { $SerializerType } from "net.minecraft.world.level.storage.loot.SerializerType"

export class $LootNbtProviderType extends $SerializerType<$NbtProvider> {
constructor(serializer0: $Serializer$$Type<$NbtProvider$$Type>)

/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.LootNbtProviderType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.LootNbtProviderTypeTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootNbtProviderType$$Type = ($LootNbtProviderType | Special.LootNbtProviderType);
}

declare module "net.minecraft.world.level.storage.loot.parameters.LootContextParam" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootContextParam$$Type<T = any> = ($LootContextParam<T>);
}

declare module "net.minecraft.world.level.storage.loot.entries.EntryGroup$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $EntryGroup$Builder$$Type = ($EntryGroup$Builder);
}

declare module "net.minecraft.world.level.storage.loot.entries.SequentialEntry$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SequentialEntry$Builder$$Type = ($SequentialEntry$Builder);
}

declare module "net.minecraft.world.level.storage.loot.LootParams" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootParams$$Type = ($LootParams);
}

declare module "net.minecraft.world.level.storage.loot.LootTable" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootTable$$Type = ($LootTable);
}

declare module "net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootPoolEntryContainer$Builder$$Type<T extends $LootPoolEntryContainer$Builder<T> = $LootPoolEntryContainer$Builder<T>> = ($LootPoolEntryContainer$Builder<T>);
}

declare module "net.minecraft.world.level.storage.LevelStorageSource$LevelDirectory" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LevelStorageSource$LevelDirectory$$Type = ($LevelStorageSource$LevelDirectory);
}

declare module "net.minecraft.world.level.storage.loot.Serializer" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Serializer$$Type<T = any> = ($Serializer<T>);
}

declare module "net.minecraft.world.level.storage.PrimaryLevelData$SpecialWorldProperty" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PrimaryLevelData$SpecialWorldProperty$$Type = ($PrimaryLevelData$SpecialWorldProperty | ("none" | "flat" | "debug"));
}

declare module "net.minecraft.world.level.storage.LevelData" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LevelData$$Type = ($LevelData);
}

declare module "net.minecraft.world.level.storage.loot.LootContext$EntityTarget" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootContext$EntityTarget$$Type = ($LootContext$EntityTarget | ("this" | "killer" | "direct_killer" | "killer_player"));
}

declare module "net.minecraft.world.level.storage.LevelSummary" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LevelSummary$$Type = ($LevelSummary);
}

declare module "net.minecraft.world.level.storage.loot.functions.CopyNameFunction$NameSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CopyNameFunction$NameSource$$Type = ($CopyNameFunction$NameSource | ("this" | "killer" | "killer_player" | "block_entity"));
}

declare module "net.minecraft.world.level.storage.loot.LootParams$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootParams$Builder$$Type = ($LootParams$Builder);
}

declare module "net.minecraft.world.level.storage.loot.predicates.AllOfCondition$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $AllOfCondition$Builder$$Type = ($AllOfCondition$Builder);
}

declare module "net.minecraft.world.level.storage.loot.predicates.ConditionUserBuilder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ConditionUserBuilder$$Type<T extends $ConditionUserBuilder<T> = $ConditionUserBuilder<T>> = ($ConditionUserBuilder<T>);
}

declare module "net.minecraft.world.level.storage.loot.parameters.LootContextParamSet$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootContextParamSet$Builder$$Type = ($LootContextParamSet$Builder);
}

declare module "net.minecraft.world.level.storage.loot.LootPool$Builder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootPool$Builder$$Type = ($LootPool$Builder);
}

declare module "net.minecraft.world.level.storage.loot.LootDataResolver" {
import { $LootDataId } from "net.minecraft.world.level.storage.loot.LootDataId"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootDataResolver$$Type = ($LootDataResolver | ((arg0: $LootDataId<T>) => T));
}

declare module "net.minecraft.world.level.storage.loot.functions.LootItemFunction$Builder" {
import { $LootItemFunction$$Type } from "net.minecraft.world.level.storage.loot.functions.LootItemFunction"

/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootItemFunction$Builder$$Type = ($LootItemFunction$Builder | (() => $LootItemFunction$$Type));
}

declare module "net.minecraft.world.level.storage.loot.predicates.LootItemCondition" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootItemCondition$$Type = ($LootItemCondition);
}

declare module "net.minecraft.world.level.storage.LevelSummary$BackupStatus" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LevelSummary$BackupStatus$$Type = ($LevelSummary$BackupStatus | ("none" | "downgrade" | "upgrade_to_snapshot"));
}

declare module "net.minecraft.world.level.storage.loot.functions.FunctionUserBuilder" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $FunctionUserBuilder$$Type<T extends $FunctionUserBuilder<T> = $FunctionUserBuilder<T>> = ($FunctionUserBuilder<T>);
}

declare module "net.minecraft.world.level.storage.LevelStorageSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LevelStorageSource$$Type = ($LevelStorageSource);
}

declare module "net.minecraft.world.level.storage.loot.LootDataManager" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootDataManager$$Type = ($LootDataManager);
}

declare module "net.minecraft.world.level.storage.loot.LootContext" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootContext$$Type = ($LootContext);
}

declare module "net.minecraft.world.level.storage.PlayerDataStorage" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PlayerDataStorage$$Type = ($PlayerDataStorage);
}

declare module "net.minecraft.world.level.storage.WorldData" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $WorldData$$Type = ($WorldData);
}

declare module "net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $LootPoolEntryContainer$$Type = ($LootPoolEntryContainer);
}

