declare module "net.minecraft.world.level.levelgen.flat.FlatLayerInfo" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $FlatLayerInfo$$Type = ($FlatLayerInfo);
}

declare module "net.minecraft.world.level.levelgen.flat.FlatLevelGeneratorPreset" {
import { $Codec } from "com.mojang.serialization.Codec"
import { $Holder, $Holder$$Type } from "net.minecraft.core.Holder"
import { $FlatLevelGeneratorSettings, $FlatLevelGeneratorSettings$$Type } from "net.minecraft.world.level.levelgen.flat.FlatLevelGeneratorSettings"
import { $Item, $Item$$Type } from "net.minecraft.world.item.Item"
import { $Record } from "java.lang.Record"

export class $FlatLevelGeneratorPreset extends $Record {
static readonly "CODEC": $Codec<$Holder<$FlatLevelGeneratorPreset>>
static readonly "DIRECT_CODEC": $Codec<$FlatLevelGeneratorPreset>

constructor(holder0: $Holder$$Type<$Item$$Type>, flatLevelGeneratorSettings1: $FlatLevelGeneratorSettings$$Type)

public "displayItem"(): $Holder<$Item>
public "settings"(): $FlatLevelGeneratorSettings
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenFlatLevelGeneratorPreset
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenFlatLevelGeneratorPresetTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $FlatLevelGeneratorPreset$$Type = ($FlatLevelGeneratorPreset | Special.WorldgenFlatLevelGeneratorPreset);
}

declare module "net.minecraft.world.level.levelgen.flat.FlatLevelGeneratorSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $FlatLevelGeneratorSettings$$Type = ($FlatLevelGeneratorSettings);
}

