declare module "net.minecraft.world.item.armortrim.TrimPattern" {
import { $ResourceLocation, $ResourceLocation$$Type } from "net.minecraft.resources.ResourceLocation"
import { $Codec } from "com.mojang.serialization.Codec"
import { $Holder, $Holder$$Type } from "net.minecraft.core.Holder"
import { $Component, $Component$$Type } from "net.minecraft.network.chat.Component"
import { $Item, $Item$$Type } from "net.minecraft.world.item.Item"
import { $Record } from "java.lang.Record"
import { $TrimMaterial$$Type } from "net.minecraft.world.item.armortrim.TrimMaterial"

export class $TrimPattern extends $Record {
static readonly "CODEC": $Codec<$Holder<$TrimPattern>>
static readonly "DIRECT_CODEC": $Codec<$TrimPattern>

constructor(resourceLocation0: $ResourceLocation$$Type, holder1: $Holder$$Type<$Item$$Type>, component2: $Component$$Type)

public "assetId"(): $ResourceLocation
public "copyWithStyle"(holder0: $Holder$$Type<$TrimMaterial$$Type>): $Component
public "description"(): $Component
public "templateItem"(): $Holder<$Item>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.TrimPattern
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.TrimPatternTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $TrimPattern$$Type = ($TrimPattern | Special.TrimPattern);
}

declare module "net.minecraft.world.item.armortrim.TrimMaterial" {
import { $Codec } from "com.mojang.serialization.Codec"
import { $Holder, $Holder$$Type } from "net.minecraft.core.Holder"
import { $Component, $Component$$Type } from "net.minecraft.network.chat.Component"
import { $Item, $Item$$Type } from "net.minecraft.world.item.Item"
import { $Map, $Map$$Type } from "java.util.Map"
import { $ArmorMaterials, $ArmorMaterials$$Type } from "net.minecraft.world.item.ArmorMaterials"
import { $Record } from "java.lang.Record"

export class $TrimMaterial extends $Record {
static readonly "CODEC": $Codec<$Holder<$TrimMaterial>>
static readonly "DIRECT_CODEC": $Codec<$TrimMaterial>

constructor(string0: string, holder1: $Holder$$Type<$Item$$Type>, float2: float, map3: $Map$$Type<$ArmorMaterials$$Type, string>, component4: $Component$$Type)

public "assetName"(): string
public static "create"(string0: string, item1: $Item$$Type, float2: float, component3: $Component$$Type, map4: $Map$$Type<$ArmorMaterials$$Type, string>): $TrimMaterial
public "description"(): $Component
public "ingredient"(): $Holder<$Item>
public "itemModelIndex"(): float
public "overrideArmorMaterials"(): $Map<$ArmorMaterials, string>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.TrimMaterial
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.TrimMaterialTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $TrimMaterial$$Type = ($TrimMaterial | Special.TrimMaterial);
}

