declare module "net.minecraft.world.item.alchemy.Potion" {
import { $List } from "java.util.List"
import { $MobEffectInstance, $MobEffectInstance$$Type } from "net.minecraft.world.effect.MobEffectInstance"
import { $IForgePotion } from "net.minecraftforge.common.extensions.IForgePotion"
import { $ItemStack$$Type } from "net.minecraft.world.item.ItemStack"

export class $Potion implements $IForgePotion {
constructor(...mobEffectInstance0s: $MobEffectInstance$$Type[])
constructor(string0: string, ...mobEffectInstance1s: $MobEffectInstance$$Type[])

public static "byName"(string0: string): $Potion
public "getEffects"(): $List<$MobEffectInstance>
public "getName"(string0: string): string
public "hasInstantEffects"(): boolean
public "isFoil"(itemStack0: $ItemStack$$Type): boolean
get "effects"(): $List<$MobEffectInstance>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.Potion
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.PotionTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Potion$$Type = ($Potion | Special.Potion);
}

