declare module "net.minecraft.stats.Stats" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Stats$$Type = ($Stats);
}

declare module "net.minecraft.stats.StatFormatter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StatFormatter$$Type = ($StatFormatter | ((arg0: integer) => string));
}

declare module "net.minecraft.stats.RecipeBook" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RecipeBook$$Type = ($RecipeBook);
}

declare module "net.minecraft.stats.ServerStatsCounter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ServerStatsCounter$$Type = ($ServerStatsCounter);
}

declare module "net.minecraft.stats.StatsCounter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StatsCounter$$Type = ($StatsCounter);
}

declare module "net.minecraft.stats.Stat" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Stat$$Type<T = any> = ($Stat<T> | string);
}

declare module "net.minecraft.stats.RecipeBookSettings" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RecipeBookSettings$$Type = ($RecipeBookSettings);
}

declare module "net.minecraft.stats.ServerRecipeBook" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $ServerRecipeBook$$Type = ($ServerRecipeBook);
}

declare module "net.minecraft.stats.StatType" {
import { $Registry, $Registry$$Type } from "net.minecraft.core.Registry"
import { $Consumer$$Type } from "java.util.function.Consumer"
import { $Stat, $Stat$$Type } from "net.minecraft.stats.Stat"
import { $Component } from "net.minecraft.network.chat.Component"
import { $Iterator } from "java.util.Iterator"
import { $StatFormatter$$Type } from "net.minecraft.stats.StatFormatter"
import { $Spliterator } from "java.util.Spliterator"
import { $Iterable } from "java.lang.Iterable"

export class $StatType<T = any> implements $Iterable<$Stat<T>> {
constructor(registry0: $Registry$$Type<T>)

public "contains"(t0: T): boolean
public "forEach"(consumer0: $Consumer$$Type<$Stat$$Type<T>>): void
public "get"(t0: T, statFormatter1: $StatFormatter$$Type): $Stat<T>
public "get"(t0: T): $Stat<T>
public "getDisplayName"(): $Component
public "getRegistry"(): $Registry<T>
public "getTranslationKey"(): string
public "iterator"(): $Iterator<$Stat<T>>
public "spliterator"(): $Spliterator<$Stat<T>>
[Symbol.iterator](): IterableIterator<$Stat<T>>;
get "displayName"(): $Component
get "registry"(): $Registry<T>
get "translationKey"(): string
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.StatType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.StatTypeTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $StatType$$Type<T = any> = ($StatType<T> | Special.StatType);
}

