declare module "net.minecraft.sounds.SoundSource" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SoundSource$$Type = ($SoundSource | ("master" | "music" | "records" | "weather" | "blocks" | "hostile" | "neutral" | "players" | "ambient" | "voice"));
}

declare module "net.minecraft.sounds.Music" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $Music$$Type = ($Music);
}

declare module "net.minecraft.sounds.SoundEvent" {
import { $ResourceLocation, $ResourceLocation$$Type } from "net.minecraft.resources.ResourceLocation"
import { $Codec } from "com.mojang.serialization.Codec"
import { $Holder } from "net.minecraft.core.Holder"
import { $FriendlyByteBuf$$Type } from "net.minecraft.network.FriendlyByteBuf"

export class $SoundEvent {
static readonly "CODEC": $Codec<$Holder<$SoundEvent>>
static readonly "DIRECT_CODEC": $Codec<$SoundEvent>

public static "createFixedRangeEvent"(resourceLocation0: $ResourceLocation$$Type, float1: float): $SoundEvent
public static "createVariableRangeEvent"(resourceLocation0: $ResourceLocation$$Type): $SoundEvent
public "getLocation"(): $ResourceLocation
public "getRange"(float0: float): float
public static "readFromNetwork"(friendlyByteBuf0: $FriendlyByteBuf$$Type): $SoundEvent
public "writeToNetwork"(friendlyByteBuf0: $FriendlyByteBuf$$Type): void
get "location"(): $ResourceLocation
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.SoundEvent
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.SoundEventTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SoundEvent$$Type = ($SoundEvent | Special.SoundEvent);
}

