declare module "net.minecraft.world.level.levelgen.placement.PlacedFeature" {
import { $HolderSet } from "net.minecraft.core.HolderSet"
import { $RandomSource$$Type } from "net.minecraft.util.RandomSource"
import { $Record } from "java.lang.Record"
import { $ChunkGenerator$$Type } from "net.minecraft.world.level.chunk.ChunkGenerator"
import { $List, $List$$Type } from "java.util.List"
import { $ConfiguredFeature, $ConfiguredFeature$$Type } from "net.minecraft.world.level.levelgen.feature.ConfiguredFeature"
import { $Codec } from "com.mojang.serialization.Codec"
import { $Holder, $Holder$$Type } from "net.minecraft.core.Holder"
import { $Stream } from "java.util.stream.Stream"
import { $WorldGenLevel$$Type } from "net.minecraft.world.level.WorldGenLevel"
import { $BlockPos$$Type } from "net.minecraft.core.BlockPos"
import { $PlacementModifier, $PlacementModifier$$Type } from "net.minecraft.world.level.levelgen.placement.PlacementModifier"

export class $PlacedFeature extends $Record {
static readonly "CODEC": $Codec<$Holder<$PlacedFeature>>
static readonly "DIRECT_CODEC": $Codec<$PlacedFeature>
static readonly "LIST_CODEC": $Codec<$HolderSet<$PlacedFeature>>
static readonly "LIST_OF_LISTS_CODEC": $Codec<$List<$HolderSet<$PlacedFeature>>>

constructor(holder0: $Holder$$Type<$ConfiguredFeature$$Type<any, any>>, list1: $List$$Type<$PlacementModifier$$Type>)

public "feature"(): $Holder<$ConfiguredFeature<any, any>>
public "getFeatures"(): $Stream<$ConfiguredFeature<any, any>>
public "place"(worldGenLevel0: $WorldGenLevel$$Type, chunkGenerator1: $ChunkGenerator$$Type, randomSource2: $RandomSource$$Type, blockPos3: $BlockPos$$Type): boolean
public "placeWithBiomeCheck"(worldGenLevel0: $WorldGenLevel$$Type, chunkGenerator1: $ChunkGenerator$$Type, randomSource2: $RandomSource$$Type, blockPos3: $BlockPos$$Type): boolean
public "placement"(): $List<$PlacementModifier>
get "features"(): $Stream<$ConfiguredFeature<any, any>>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenPlacedFeature
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenPlacedFeatureTag
}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PlacedFeature$$Type = ($PlacedFeature | Special.WorldgenPlacedFeature);
}

declare module "net.minecraft.world.level.levelgen.placement.PlacementModifierType" {
import { $CountOnEveryLayerPlacement } from "net.minecraft.world.level.levelgen.placement.CountOnEveryLayerPlacement"
import { $EnvironmentScanPlacement } from "net.minecraft.world.level.levelgen.placement.EnvironmentScanPlacement"
import { $HeightRangePlacement } from "net.minecraft.world.level.levelgen.placement.HeightRangePlacement"
import { $SurfaceWaterDepthFilter } from "net.minecraft.world.level.levelgen.placement.SurfaceWaterDepthFilter"
import { $NoiseBasedCountPlacement } from "net.minecraft.world.level.levelgen.placement.NoiseBasedCountPlacement"
import { $BlockPredicateFilter } from "net.minecraft.world.level.levelgen.placement.BlockPredicateFilter"
import { $RandomOffsetPlacement } from "net.minecraft.world.level.levelgen.placement.RandomOffsetPlacement"
import { $InSquarePlacement } from "net.minecraft.world.level.levelgen.placement.InSquarePlacement"
import { $NoiseThresholdCountPlacement } from "net.minecraft.world.level.levelgen.placement.NoiseThresholdCountPlacement"
import { $RarityFilter } from "net.minecraft.world.level.levelgen.placement.RarityFilter"
import { $Codec, $Codec$$Type } from "com.mojang.serialization.Codec"
import { $CountPlacement } from "net.minecraft.world.level.levelgen.placement.CountPlacement"
import { $HeightmapPlacement } from "net.minecraft.world.level.levelgen.placement.HeightmapPlacement"
import { $PlacementModifier, $PlacementModifier$$Type } from "net.minecraft.world.level.levelgen.placement.PlacementModifier"
import { $SurfaceRelativeThresholdFilter } from "net.minecraft.world.level.levelgen.placement.SurfaceRelativeThresholdFilter"
import { $CarvingMaskPlacement } from "net.minecraft.world.level.levelgen.placement.CarvingMaskPlacement"
import { $BiomeFilter } from "net.minecraft.world.level.levelgen.placement.BiomeFilter"

export interface $PlacementModifierType<P extends $PlacementModifier = $PlacementModifier> {
"codec"(): $Codec<P>
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Literal": Special.WorldgenPlacementModifierType
/** This field is a type stub generated by ProbeJS and shall not be used in any sense. */
"probejsInternal$$Tag": Special.WorldgenPlacementModifierTypeTag
}

export namespace $PlacementModifierType {
const BIOME_FILTER: $PlacementModifierType<$BiomeFilter>
const BLOCK_PREDICATE_FILTER: $PlacementModifierType<$BlockPredicateFilter>
const CARVING_MASK_PLACEMENT: $PlacementModifierType<$CarvingMaskPlacement>
const COUNT: $PlacementModifierType<$CountPlacement>
const COUNT_ON_EVERY_LAYER: $PlacementModifierType<$CountOnEveryLayerPlacement>
const ENVIRONMENT_SCAN: $PlacementModifierType<$EnvironmentScanPlacement>
const HEIGHTMAP: $PlacementModifierType<$HeightmapPlacement>
const HEIGHT_RANGE: $PlacementModifierType<$HeightRangePlacement>
const IN_SQUARE: $PlacementModifierType<$InSquarePlacement>
const NOISE_BASED_COUNT: $PlacementModifierType<$NoiseBasedCountPlacement>
const NOISE_THRESHOLD_COUNT: $PlacementModifierType<$NoiseThresholdCountPlacement>
const RANDOM_OFFSET: $PlacementModifierType<$RandomOffsetPlacement>
const RARITY_FILTER: $PlacementModifierType<$RarityFilter>
const SURFACE_RELATIVE_THRESHOLD_FILTER: $PlacementModifierType<$SurfaceRelativeThresholdFilter>
const SURFACE_WATER_DEPTH_FILTER: $PlacementModifierType<$SurfaceWaterDepthFilter>
}
export abstract class $PlacementModifierType$$Static<P extends $PlacementModifier = $PlacementModifier> implements $PlacementModifierType<P> {
static readonly "BIOME_FILTER": $PlacementModifierType<$BiomeFilter>
static readonly "BLOCK_PREDICATE_FILTER": $PlacementModifierType<$BlockPredicateFilter>
static readonly "CARVING_MASK_PLACEMENT": $PlacementModifierType<$CarvingMaskPlacement>
static readonly "COUNT": $PlacementModifierType<$CountPlacement>
static readonly "COUNT_ON_EVERY_LAYER": $PlacementModifierType<$CountOnEveryLayerPlacement>
static readonly "ENVIRONMENT_SCAN": $PlacementModifierType<$EnvironmentScanPlacement>
static readonly "HEIGHTMAP": $PlacementModifierType<$HeightmapPlacement>
static readonly "HEIGHT_RANGE": $PlacementModifierType<$HeightRangePlacement>
static readonly "IN_SQUARE": $PlacementModifierType<$InSquarePlacement>
static readonly "NOISE_BASED_COUNT": $PlacementModifierType<$NoiseBasedCountPlacement>
static readonly "NOISE_THRESHOLD_COUNT": $PlacementModifierType<$NoiseThresholdCountPlacement>
static readonly "RANDOM_OFFSET": $PlacementModifierType<$RandomOffsetPlacement>
static readonly "RARITY_FILTER": $PlacementModifierType<$RarityFilter>
static readonly "SURFACE_RELATIVE_THRESHOLD_FILTER": $PlacementModifierType<$SurfaceRelativeThresholdFilter>
static readonly "SURFACE_WATER_DEPTH_FILTER": $PlacementModifierType<$SurfaceWaterDepthFilter>

}
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PlacementModifierType$$Type<P extends $PlacementModifier = $PlacementModifier> = ($PlacementModifierType<P> | Special.WorldgenPlacementModifierType | (() => $Codec$$Type<P>));
}

declare module "net.minecraft.world.level.levelgen.placement.EnvironmentScanPlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $EnvironmentScanPlacement$$Type = ($EnvironmentScanPlacement);
}

declare module "net.minecraft.world.level.levelgen.placement.RepeatingPlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RepeatingPlacement$$Type = ($RepeatingPlacement);
}

declare module "net.minecraft.world.level.levelgen.placement.HeightmapPlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $HeightmapPlacement$$Type = ($HeightmapPlacement);
}

declare module "net.minecraft.world.level.levelgen.placement.PlacementFilter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PlacementFilter$$Type = ($PlacementFilter);
}

declare module "net.minecraft.world.level.levelgen.placement.NoiseThresholdCountPlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $NoiseThresholdCountPlacement$$Type = ($NoiseThresholdCountPlacement);
}

declare module "net.minecraft.world.level.levelgen.placement.NoiseBasedCountPlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $NoiseBasedCountPlacement$$Type = ($NoiseBasedCountPlacement);
}

declare module "net.minecraft.world.level.levelgen.placement.PlacementContext" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PlacementContext$$Type = ($PlacementContext);
}

declare module "net.minecraft.world.level.levelgen.placement.CountPlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CountPlacement$$Type = ($CountPlacement);
}

declare module "net.minecraft.world.level.levelgen.placement.HeightRangePlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $HeightRangePlacement$$Type = ($HeightRangePlacement);
}

declare module "net.minecraft.world.level.levelgen.placement.BiomeFilter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BiomeFilter$$Type = ($BiomeFilter);
}

declare module "net.minecraft.world.level.levelgen.placement.BlockPredicateFilter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $BlockPredicateFilter$$Type = ($BlockPredicateFilter);
}

declare module "net.minecraft.world.level.levelgen.placement.RarityFilter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RarityFilter$$Type = ($RarityFilter);
}

declare module "net.minecraft.world.level.levelgen.placement.SurfaceRelativeThresholdFilter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SurfaceRelativeThresholdFilter$$Type = ($SurfaceRelativeThresholdFilter);
}

declare module "net.minecraft.world.level.levelgen.placement.CaveSurface" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CaveSurface$$Type = ($CaveSurface | ("ceiling" | "floor"));
}

declare module "net.minecraft.world.level.levelgen.placement.CarvingMaskPlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CarvingMaskPlacement$$Type = ($CarvingMaskPlacement);
}

declare module "net.minecraft.world.level.levelgen.placement.InSquarePlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $InSquarePlacement$$Type = ($InSquarePlacement);
}

declare module "net.minecraft.world.level.levelgen.placement.SurfaceWaterDepthFilter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $SurfaceWaterDepthFilter$$Type = ($SurfaceWaterDepthFilter);
}

declare module "net.minecraft.world.level.levelgen.placement.PlacementModifier" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $PlacementModifier$$Type = ($PlacementModifier);
}

declare module "net.minecraft.world.level.levelgen.placement.RandomOffsetPlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $RandomOffsetPlacement$$Type = ($RandomOffsetPlacement);
}

declare module "net.minecraft.world.level.levelgen.placement.CountOnEveryLayerPlacement" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
/** Use `Internal.{Type}` and `Internal.{Type}_` for referencing this type in JS file */
export type $CountOnEveryLayerPlacement$$Type = ($CountOnEveryLayerPlacement);
}

